### ISSUE TITLE
Thickness not disabled togheter with the mixer

### ISSUE THREAD

**Issue by Alagoss** [stijnwop/manureSystem#103]
Placeable liquid manure storage mods that have the mixer disabled with `hasMixer="false"` still get _thickness_ in the game. 
Disabling thickness when the mixer is disabled would be a solution.

Example:
https://www.farming-simulator.com/mod.php?lang=en&country=nl&mod_id=163387

**Comment by stijnwop** [comment]
Fixed, please test.

**Comment by Alagoss** [comment]
Confirmed fix 👍
