### ISSUE TITLE
Questions: Longer slurry hoses + Fillspeed

### ISSUE THREAD

**Issue by Timothy-V** [stijnwop/manureSystem#104]
Really enjoying your mod, fantastic work!

First question: I would like to make some longer hoses (25 & 50 meters) to be able to pump from the farm to a nearby field. Editing the hose xml is not the problem. I can't figure out the correct Z positions for the componentJoints and hose main components in the i3d file though. I have applied Z Scale to the main_components for extending them, is that the correct way? And does the i3d.shapes file need to be edited? New to modding, so maybe I'm not doing it the correct way.

Second question: Is it possible to change the filling speed of this mod?

Thanks!

![25mhose](https://user-images.githubusercontent.com/47175711/83943632-fc51b880-a7fd-11ea-89e1-1f5e973eaf60.jpg)

**Comment by KITT3000** [comment]
But you have a hose extension to buy and you can connect them to any length.

**Comment by stijnwop** [comment]
1) The whole hose movement is not designed for hoses longer than 5 meters pretty much. The latest github version has a 5 meter one. 

So I wouldn't bother trying if I was you.

2) Yes just alter the tanker in question pump speed, they're all set to more realistic values.
