### ISSUE TITLE
Question - pipe holder

### ISSUE THREAD

**Issue by zcaalock** [stijnwop/manureSystem#105]
Is it possible to attach pipe to trailer? So it would be possible to carry it around?

**Comment by stijnwop** [comment]
Yes? Did you even try it out? 

Tankers have parking places and those support the entries..

Not even sure what you're asking at all.. lol

**Comment by zcaalock** [comment]
nvm got it to work
![pipe](https://user-images.githubusercontent.com/24411061/83952263-ec56ca80-a837-11ea-956b-dfb7a6bae03f.jpg)
