### ISSUE TITLE
Gülle System funktoniert seit LS19 version 1.6.0 nicht richtig

### ISSUE THREAD

**Issue by michel5998** [stijnwop/manureSystem#107]
um auf den Punkt zu kommen, ich kann nur noch bei wenigen fahrzeugen die schläuche auf die schlauchhalter legen und in der güllegrube, was zu dem mod gehört, steht wasser, ich kann zwar noch was einlagern aber nicht aufrühren

**Comment by Snickers125** [comment]
Hi, I would appreciate some more information i.e.

- full log.txt (just drag and drop the file here)
- which MS version are you using? github or ModHub?
- is this SP, MP, or dedicated server? 
- drop a screenshot of the pit, filled with water

**Comment by michel5998** [comment]
first it's the latest github version in sp
second: 
[log.txt](https://github.com/stijnwop/manureSystem/files/4777008/log.txt)
an 3rd: 
![fsScreen_2020_06_14_20_28_09](https://user-images.githubusercontent.com/49126733/84601015-a7f1ad00-ae7d-11ea-9e07-5afc8de55ed9.png)

**Comment by m0bscene** [comment]
ich würde erstmal den ganzen Modordner aufräumen,und alles was Errors und warnings verursacht, rausnehmen . Auch den FS19_READynamicDirt Mod

**Comment by stijnwop** [comment]
What map are you playing on? That water plane is an issue of some maps and has nothing todo with the manure system mod itself.

**Comment by stijnwop** [comment]
Closing due to lack of information.
