### ISSUE TITLE
Errors in the Version 1.0.9.2 

### ISSUE THREAD

**Issue by Omat1998** [stijnwop/manureSystem#109]
I´ve got these Errrors in the newest Version 1.0.9.2

mods/FS19_manureSystem/resources/assets/connectionHoses/flanges_normal.png'.
mods/FS19_manureSystem/resources/assets/connectionHoses/flanges_specular.png'.
mods/FS19_manureSystem/$data/shared/connectionHoses/hoses_normal.dds'.
mods/FS19_manureSystem/$data/shared/connectionHoses/hoses_specular.dds'.
mods/FS19_manureSystem/$data/shared/connectionHoses/frontConnector_normal.dds'.
mods/FS19_manureSystem/$data/shared/connectionHoses/frontConnector_specular.dds'.
mods/FS19_manureSystem/$data/shared/connectionHoses/connectors_normal.dds'.
mods/FS19_manureSystem/$data/shared/connectionHoses/connectors_specular.dds'.

I think that its easy to fix, but i don´t know where these files are 😄

**Comment by stijnwop** [comment]
My bad, updated the zip of the release! :)

**Comment by Omat1998** [comment]
Nice, thank you mate ;D
