### ISSUE TITLE
Warning (script): 'bitXOR': Argument 1 has wrong type. Expected: UInt. Actual: Nil 

### ISSUE THREAD

**Issue by Iab72** [stijnwop/manureSystem#11]
Hi thanks for the mod, after i active the Manure System in my game , and log to the game when i sleep for 10 hour in the game , and  i picked a egg box and put it in the storage house by GTX , the game freeze for 5 second and after that the ( R bottom ) doesn't work for Fasten the belt or customizing  the vehicle , and several things . Her is my log
[log.txt](https://github.com/stijnwop/manureSystem/files/4318449/log.txt)

**Comment by stijnwop** [comment]
Looks like to me you're picking up an object that gets deleted directly.

Big change there's a mod conflicting there.. else it should have happen with the vanilla pickup too.
