### ISSUE TITLE
1.0.9.2beta und Dediserver

### ISSUE THREAD

**Issue by ProdaxCH** [stijnwop/manureSystem#110]
Guten Tag
Seit 1.0.9.2beta ist auf Dedi Server mit der Hof Bergmann Problem das Schläuche nicht erkannt werden, teilweise nicht vorhanden sind oder nicht gekauft werden können. Fehler im Zusammenhang mit Universal tank pack. 
Im Singel Player besteht der Fehler nicht auch die Log im Singel Player ist sauber, auch mit 1.0.9.1beta ist der Fehler nicht vorhanden weder in Multiplayer noch im Singel Player die Log vom Server mit aktuellen beta Version. [https://cdn.discordapp.com/attachments/557220860277030914/723652668098215986/Server_log.txt](url)
Besten Dank

**Comment by stijnwop** [comment]
Report it to the dude who did that pack.

**Comment by ProdaxCH** [comment]
Ist auch gemeldet, frage mich nur warum hat das pack mit beta 1.0.9.0 und mit beta 1.0.9.1 funktioniert aber nun mit 1.0.9.2 nicht mehr geht und das Problem nur auf Dedi da ist und im Singel Player nicht.
