### ISSUE TITLE
manure system issue

### ISSUE THREAD

**Issue by answermanitou** [stijnwop/manureSystem#111]
Hello. I was using the manure system mod from the beginning of new map untill I need to use courseplay(last ver 31) with liquids transportations. Such as refill field slurry tank from different slurry pit. Courseplay doesn't respond any slurry pits. Even when I drive to pit there are no action button in the Hub. Only with attached hoses. May be its nice work with many people in multiplayer. But in single its very hard.
So 
I try to disable manure mod. But now I can't load my save game. Its loading for a cyrcle. Before disabling manure mod I sell all components of it.
Can U help me
Restarting by new game is not exit because I play in current very long time.
Thanks

**Comment by stijnwop** [comment]
Did you update to the latest release here? That one is fully compatible with CP.

**Comment by answermanitou** [comment]
> Did you update to the latest release here? That one is fully compatible with CP.

Yes. I always check for a new one. 
I will try again to rewrite course tomorrow.

**Comment by answermanitou** [comment]
Hello
After I reinstall manuremod directly from this site the CP driver is work fine with refilling course. 
Next I want to sell one of slurry pit but before drive with manure pump, 4 hoses. Attach all. Open valves and when I presst Ctrl+r to enable pumb - -the game is crashed down. Check on log.txt bellow
[log.txt](https://github.com/stijnwop/manureSystem/files/4824761/log.txt)

**Comment by stijnwop** [comment]
You want to sell some slurry?
Thats not supported natively by the manure system.. so I assume you're running with a modcompany object.
By looking at the log the object that is prepared by the modcompany mod is missing a method. Make sure you updated those mods.. else you will have to forward it to them.

**Comment by answermanitou** [comment]
> You want to sell some slurry?
> Thats not supported natively by the manure system.. so I assume you're running with a modcompany object.
> By looking at the log the object that is prepared by the modcompany mod is missing a method. Make sure you updated those mods.. else you will have to forward it to them.

No i Didnt want to sell slurry. I want to pumping from one reservoir to other. Yes that slurry reservoir is an extension from GCmod  for animals pit.

**Comment by stijnwop** [comment]
Did you update the GC mod?

**Comment by answermanitou** [comment]
Sorry for a quite. My laptop is burn and I don't play  last week. 
Before it I update all mods such as manure, gc and cp. All works great. But I can understand why when I staying near cow or pig or bga liquid manure barrel there are no information about its filling level? Only when I open seasons and check pastures there is has information about manure level. But on the bga must be digested liquid and how much is there I don't know
