### ISSUE TITLE
Incorrect Texture Paths for connectionHoses asset

### ISSUE THREAD

**Issue by L2KPerma** [stijnwop/manureSystem#112]
In 1.0.9.2 the connectionHoses asset is attempting to look for textures in the $data folder within the Manure System files rather than the $data folder of the game.

Also missing the normal and specular images for the flanges within the same asset.

**Comment by stijnwop** [comment]
Did you re-download the release files again? Updated that not so long after someone else reported the same

**Comment by L2KPerma** [comment]
Thought I had downloaded after that, but turns out I must of done so before. As indeed I no longer have the errors.
