### ISSUE TITLE
Multiple Fill types

### ISSUE THREAD

**Issue by 206airmail** [stijnwop/manureSystem#114]
Is there anyway to make this work with multiple fill types?
I have a trailer with water and diesel both on it, however, it only fills the 1st fillunitindex. Is there anyway to make it fill whichever fill type depending on what you are connected to? Or perhaps be able to assign fillunitindex values to connectors?
Thanks!

**Comment by stijnwop** [comment]
You already can assign a fillunitIndex to a connector.

<connector type="..." fullUnitIndex="2" etc.. />

Index 1 is default.
