### ISSUE TITLE
Filling doesn't work

### ISSUE THREAD

**Issue by hiredgun** [stijnwop/manureSystem#116]
The pump doesn't work. Tried it with different tanks. Nothing happens after hitting R. The engine is on.

![image](https://user-images.githubusercontent.com/2885483/86530826-68d2dc80-bebc-11ea-87fd-22e98e7e134d.png)

**Comment by stijnwop** [comment]
Does that tanker support manure flow?

If yes, you will need to open the flow on the connector of the tanker.

**Comment by hiredgun** [comment]
It's the Veenhuis Premium Integral 30000 from the supported tankers list https://github.com/stijnwop/manureSystem#out-of-the-box-support. It doesn't have the valve to open the flow. Tried also with SamsonAgro PGII35m, it has the valve and I opened the flow but there is the same issue.

**Comment by stijnwop** [comment]
Do you have liquid manure into that pit + do you own the thing?

**Comment by hiredgun** [comment]
yes

**Comment by hiredgun** [comment]
I found the issue. The problem was conflicting key bindings. After changing the binding for the pump it now works. Sorry for the noise but maybe this will help in case someone has the same issue.
