### ISSUE TITLE
Not all prerequisites of specialization FS19_manureSystem.manureSystemPumpMotor are fulfilled

### ISSUE THREAD

**Issue by IosifStalin** [stijnwop/manureSystem#125]
Please help me! I make a mod in which there are two types of body, one of which is a barrel for transporting fertilizers. But when adding a pump, this error appears
```
`[MS Info]: Adding ManureSystemPumpMotor to: 'KamAZ_65115_Spoler_Pricep.Kamaz45143_tank
 [MS Info]: Adding ManureSystemConnector to: 'KamAZ_65115_Spoler_Pricep.Kamaz45143_tank
 Error: Not all prerequisites of specialization FS19_manureSystem.manureSystemPumpMotor are fulfilled

Error loadVehicle: unknown type 'KamAZ_65115_Spoler_Pricep.Kamaz45143_tank' in 'C:/Users/User/Documents/My Games/FarmingSimulator2019/mods/KamAZ_65115_Spoler_Pricep/Kamaz45143.xml
```
`
This is my ModDesc
```
<specializations>
        <specialization name="addConfig" className="AddConfig" filename="scripts/AddConfig.lua"/>
		<specialization name="manureSystemVehicle" className="ManureSystemVehicle" filename="scripts/ManureSystemVehicle.lua"/>	
    </specializations>

<vehicleTypes>
        <type name="Kamaz45143" parent="carFillable" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
            <specialization name="addConfig"/>
            <specialization name="cover"/>
        </type>
		<type name="Kamaz45143_tank" parent="carFillable" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
			<specialization name="addConfig"/>
			<specialization name="manureSystemVehicle"/>
        </type>
</vehicleTypes>
```

and thi is vehicle xml

```
<manureSystem hasPumpMotor="true" hasConnectors="true" />
	<manureSystemPumpMotor isStandalone="true" litersPerSecond="150" toReachMaxEfficiencyTime="1000">
        <sounds>
            <pump template="SLURRY_02">
                <pitch indoor="0.85" outdoor="0.75"/>
            </pump>
        </sounds>
    </manureSystemPumpMotor>

    <manureSystemConnectors>
        <connector type="COUPLINGFERTILIZER" node="Сonnector1" fillUnitIndex="1"/>
        <connector type="COUPLINGFERTILIZER" node="Сonnector2" fillUnitIndex="1"/>
    </manureSystemConnectors>
```

if I remove the line hasPumpMotor="true" only connectors work

**Comment by IosifStalin** [comment]
> 
> 
> Please help me! I make a mod in which there are two types of body, one of which is a barrel for transporting fertilizers. But when adding a pump, this error appears
> 

> [MS Info]: Adding ManureSystemPumpMotor to: 'KamAZ_65115_Spoler_Pricep.Kamaz45143_tank
> > [MS Info]: Adding ManureSystemConnector to: 'KamAZ_65115_Spoler_Pricep.Kamaz45143_tank
> > Error: Not all prerequisites of specialization FS19_manureSystem.manureSystemPumpMotor are fulfilled
> > 
> > Error loadVehicle: unknown type 'KamAZ_65115_Spoler_Pricep.Kamaz45143_tank' in 'C:/Users/User/Documents/My 
> 
> > Games/FarmingSimulator2019/mods/KamAZ_65115_Spoler_Pricep/Kamaz45143.xml

> `This is mi ModDesc`
> 
> 
> `
> 
> and thi is vehicle xml
> 
> `
> 
> 
> 
> 
> 
> 
> ```
> <manureSystemConnectors>
>     <connector type="COUPLINGFERTILIZER" node="Сonnector1" fillUnitIndex="1"/>
>     <connector type="COUPLINGFERTILIZER" node="Сonnector2" fillUnitIndex="1"/>
> </manureSystemConnectors>`
> ```
> 
> if I remove the line hasPumpMotor="true" only connectors work

**Comment by KITT3000** [comment]
Add
```xml
<specialization name="powerConsumer"/>
```
before
**<specialization name="manureSystemVehicle"/>**

**Comment by IosifStalin** [comment]
> ```
> <specialization name="powerConsumer"/>
> ```

Thanks it worked. But it was still necessary to add <specialization name="fillTriggerVehicle"/> 
Thanks a lot again
