### ISSUE TITLE
 Broken machine

### ISSUE THREAD

**Issue by Chobi89** [stijnwop/manureSystem#126]
Hi,

I need help finding a mistake. The machine does not work properly. I inserted everything according to the instructions. The hose can be connected but cannot be pumped .... I'm attaching xml files.
Thanks

[XML.zip](https://github.com/stijnwop/manureSystem/files/5434808/XML.zip)

**Comment by KITT3000** [comment]
In "vehicleTypeConfiguration" you use the default vehicle type, not yours defined in modDesc.

**Comment by Chobi89** [comment]
můžete být konkrétní nemohu to dát spravně.

**Comment by KITT3000** [comment]
In line 430, 435, 440, 445, 450, 455 change `vehicleType="manureBarrel"` to `vehicleType="manurePzTF3"`. Additionally, you shouldn't use such a form for translations as `"$ l10n_No logo, no toolbox"`, instead you should have e.g. `"$ l10n_noLogo1"` and only translate exactly for each language (you shouldn't have spaces or diacritics in the title, only when translating this is used)

**Comment by Chobi89** [comment]
I fixed but still not functional pumping ....

**Comment by KITT3000** [comment]
There is nothing in the LOG?

**Comment by Chobi89** [comment]
LOG is clear.

**Comment by Chobi89** [comment]
[log.txt](https://github.com/stijnwop/manureSystem/files/5435341/log.txt)

**Comment by Chobi89** [comment]
I had the wrong value isStandalone = "true"
Thanks
