### ISSUE TITLE
How making the Smety Mod Xerion 3000 Saddle Trac frontdock pump right ?

### ISSUE THREAD

**Issue by Lactic68** [stijnwop/manureSystem#127]
Hi Wopster,

I think Smety has already contacted you but do you have planned to help him to finish his front liquid manure pump of his [Xerion 3000 Saddle Trac](https://www.farming-simulator.com/mod.php?lang=fr&country=fr&mod_id=183585&title=fs2019) ?
For now, he had to code the tank inside the front pump which is really odd and make the tractor completely unbalanced .. as you can see [here](https://scontent-cdt1-1.xx.fbcdn.net/v/t1.0-9/122998303_4459171697491563_3591427018824294499_o.jpg?_nc_cat=110&ccb=2&_nc_sid=1480c5&_nc_ohc=2P1kRuPlJ7IAX82MvPx&_nc_ht=scontent-cdt1-1.xx&oh=8f5718e43c0c071f103153df8147eb95&oe=5FBD0A80)

Again, thanks for your great mod, very good addition to the game.

**Comment by stijnwop** [comment]
No he did not, and he could have simply made the frontdock function like a frontdock with the standalone pump option. Which is done in some cases already so no need to make frontdock act like a 'tank'.

**Comment by Lactic68** [comment]
Hi Wopster,

Thank you for your quick answer. I tried to contact Smety by email but his mailbox is saturated. 
Do you think it is possible to fix his mod by editing it to make it right with your manure system ? I would like to help sorting this out but I will need a walkthrough in order to know what I have to do (XML editing only or Giants Editor).

**Comment by Lactic68** [comment]
Hi,
I have tried to edit the modDesc.xml by adding this : 
`    <specializations>
        <specialization name="manureSystemVehicle" className="ManureSystemVehicle" filename="ManureSystemVehicle.lua"/>
    </specializations>`
and this
`    <vehicleTypes>
        <type name="saddletrac" parent="baseDrivable" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
            <specialization name="cover"/>
            <specialization name="crabSteering"/>
            <specialization name="manureSystemVehicle"/>
        </type>
    </vehicleTypes>`

But when I try to buy the Xerion in the shop, nothing appears. It seems that the mod won't load. When I remove the specializations line, it works.

**Comment by KITT3000** [comment]
@Lactic68 But why are you adding this specialty to a vehicle type for a tractor instead of making a new type of vehicle for the pump itself?

**Comment by Lactic68** [comment]
@KITT3000 The pump (zunhammer_pump.xml) is an implement of this tractor which is in located in the same mod. I would gladly use your advice to do this the right way.

**Comment by KITT3000** [comment]
Pump has 
```xml
<vehicle type="manureBarrel">
```
in XML, so you so you change `manureBarrel` to your name like `pumps` and add it in modDesc

```xml
<vehicleTypes>
        <type name="pumps" parent="implement" filename="$dataS/scripts/vehicles/Vehicle.lua">
            <specialization name="turnOnVehicle"/>
            <specialization name="fillUnit"/>
            <specialization name="manureSystemVehicle"/>
        </type>
    </vehicleTypes>
```

**Comment by Lactic68** [comment]
@KITT3000 Thank you so much for your quick help 👍🏻 
Tractor, frontdockpump and tank are now OK but when I pump slurry the tank doesn't fill :-(

**Comment by KITT3000** [comment]
But this tank available in this mod?

**Comment by Lactic68** [comment]
Yes, this tank is in this mod too

**Comment by KITT3000** [comment]
Well, since when can you pump liquid wirelessly?

**Comment by Lactic68** [comment]
So we have to add one hose in this mod ? What is weird is that the modder has included some kind of small hose between frontdock and rear tank but is this purely aesthetic ?
Do you think it is fixable in Giants Editor ?

**Comment by KITT3000** [comment]
Yes, such a hose you should make.

**Comment by Lactic68** [comment]
@KITT3000 Well thank you for all your advice but creating a hose between those two elements which are not in the same i3d file is beyond my skills in Giants Editor.

**Comment by KITT3000** [comment]
It is enough to set only 2 transformGroups, one in the pump, the other next to the tank, as it is in the case of a tanker or seed drills with an additional seed hopper on the front three-point linkage

**Comment by Lactic68** [comment]
Do you have an example mod in mind which use this method ? So I can learn how to do this.
Is the fact that there are 2 different i3d file going to be an issue ?

**Comment by Lactic68** [comment]
I just checked in GE and they might be transformGroups we can use.
For the tank : Node 0>3
For the pump : Node 0>5

I just don't know how to connect them

**Comment by KITT3000** [comment]
You have an example in the machines in the base game.
Kuhn TF1500 (it might be your pump):
```xml
<connectionHoses>
        <hose inputAttacherJointIndices="1" type="TOOL_CONNECTOR_TOP_RIGHT" node="topRightPipe" length="2" diameter="0.14" isTwoPointHose="true"/>
    </connectionHoses>
```
Kuhn BTF4000 (it might be your tank):
```xml
 <connectionHoses>
        <hose inputAttacherJointIndices="1" type="TOOL_CONNECTOR_TOP_RIGHT" node="topRightPipe" length="1.5" diameter="0.14" isTwoPointHose="true"/>
    </connectionHoses>
```
John Deere 6R (the stiff pipe the hoses connect to appears when you hook up these 2 machines):
```xml
<connectionHoses>
<toolConnectorHose mountingNode="rightPipe">
            <startTarget attacherJointIndices="2 5" type="TOOL_CONNECTOR_TOP_RIGHT" node="rightPipe_frontConnector"/>
            <endTarget attacherJointIndices="1 3 4" type="TOOL_CONNECTOR_TOP_RIGHT" node="rightPipe_backConnector" straighteningFactor="2"/>
        </toolConnectorHose>
</connectionHoses>
```

**Comment by Lactic68** [comment]
Hi @KITT3000 ,
Thank you for your example. Applied to this mod I only found this : 

For the **Zunhammer_pump**, when attached to the front, some hoses appears but no connectionHoses are declared :
`<attachable>
        <inputAttacherJoints>
            <inputAttacherJoint node="front_attacher" jointType="saddletrac_front" needsLowering="false" allowsLowering="true" lowerRotLimitScale="0 0 0" lowerTransLimitScale="0 0 0" upperRotationOffset="0" lowerRotationOffset="0">
                <objectChange node="hose" visibilityActive="true" visibilityInactive="false"/>
            </inputAttacherJoint>
        </inputAttacherJoints>
    </attachable>`

For the **Zunhammer tank** only one connectionHoses is declared but it is for the back of the tank (to connect some implement):
` <connectionHoses>
        <hose inputAttacherJointIndices="1" type="TOOL_CONNECTOR_TOP_RIGHT" node="topRightPipe" length="1.5" diameter="0.14" straighteningFactor="1" isTwoPointHose="true" />
    </connectionHoses>`
About this tank, there is indeed a node named "hose_point" located on the far front of the tank (not directly on it) but it is not used in any way. Perhaps some collision issue when passing through the tractor body ? What do you think ?

For the **Xerion 3000 Saddle Trac**, lot of connectionHoses are declared, here is what I found. I am intrigued why has Smety not activated the rightPipe (by commenting it) : 
`<connectionHoses>
        

       <toolConnectorHose mountingNode="pipe1">
            <startTarget attacherJointIndices="6" type="TOOL_CONNECTOR_BOTTOM_01" node="bottomPipe011"/>
            <endTarget attacherJointIndices="1 2 3" type="TOOL_CONNECTOR_BOTTOM_01" node="bottomPipe001"/>
        </toolConnectorHose>

        <toolConnectorHose mountingNode="pipe2">
            <startTarget attacherJointIndices="6" type="TOOL_CONNECTOR_BOTTOM_02" node="bottomPipe021"/>
            <endTarget attacherJointIndices="1 2 3" type="TOOL_CONNECTOR_BOTTOM_02" node="bottomPipe002"/>
        </toolConnectorHose>

        <toolConnectorHose mountingNode="pipe3">
            <startTarget attacherJointIndices="6" type="TOOL_CONNECTOR_BOTTOM_03" node="bottomPipe031"/>
            <endTarget attacherJointIndices="1 2 3" type="TOOL_CONNECTOR_BOTTOM_03" node="bottomPipe003"/>
        </toolConnectorHose>

        <toolConnectorHose mountingNode="pipe4">
            <startTarget attacherJointIndices="6" type="TOOL_CONNECTOR_BOTTOM_04" node="bottomPipe041"/>
            <endTarget attacherJointIndices="1 2 3" type="TOOL_CONNECTOR_BOTTOM_04" node="bottomPipe004"/>
        </toolConnectorHose>
		
		<toolConnectorHose mountingNode="localHoses">
		    
			<startTarget attacherJointIndices="5 6" type="TOOL_CONNECTOR_TOP_RIGHT" node="hoseEndNode01"/>
            <endTarget attacherJointIndices="1 2 3" type="TOOL_CONNECTOR_TOP_RIGHT" node="hoseStartNode02"/>
        </toolConnectorHose>
    </connectionHoses>`

I can't reach Smety (his mailbox has overquota issue) and I don't have any facebook account to messenger. I don't think that he is looking at the Giants Forums where users have issue with this mod.
So this is only a first humble attempt to sort this out and to do this right with your kindful help (if it doesn't bother you of course). I wonder why Smety didn't contact you or Wopster in his creation process.

**Comment by Lactic68** [comment]
@KITT3000 
Some news on  [Smety's facebook](https://fr-fr.facebook.com/cmtsoftware/photos/a.1679865252228614/2741098192771976/?type=3&__tn__=-R) (CMT Software). Apparently he has tried multiple ways of doing it right to make the rear tank the real tank and not the pump but so far unsuccessfully, I quote : 

> CMT software to Michael Döringer :  pump and tank in one, doest work arm filling.. I test 1. zunhammer is configuration 2. zunhammer is one tool, 3. zunhammer is pump and tank (2 tools) problem is arm collision, Manure system..

An other comment says that @stijnwop has a WIP about the zunhammer Profifant, I quote : 

> Tobi Wittmann CMT software
Wopster is writing a script for the zunhammer Profifant, it's the same system, but it's work in Progress

> Michael Döringer CMT software maybe contacting Wopster? Maybe he has an good idea? He is although working on a front filling arm.

**Comment by Lactic68** [comment]
Smety has published an [update](https://www.farming-simulator.com/mod.php?lang=fr&country=fr&mod_id=183585&title=fs2019) and yet the manure system works nicely with it. The tank is still in the frontdock pump but the weight balance is fixed and same for the filling display.

I will close this issue now, thank you for your help @KITT3000 and have a nice day 👍🏻

**Comment by stijnwop** [comment]
There's just no need for a tank in the dock.. thats also not how it's suppose to work.

In my support_en channel on Discord I helped a guy who also needed to setup a frontdock.
```
isStandalone="true" useStandalonePumpText="false"
```

Key is to add those to the pumpMotor entry.

**Comment by Lactic68** [comment]
Hi @stijnwop , thank you for your advice but right now I can't reach Smety (I do not have a facebook account).
Maybe you could offer him some help by sending him a facebook messenger and invite him to your discord support server ?

I'm sure his mod will be even better with you two working together to make this right ; -)
