### ISSUE TITLE
the sleeve does not attach to the connector

### ISSUE THREAD

**Issue by sokur196** [stijnwop/manureSystem#131]
Good day!
My name is Nikita , I faced such a problem when registering a connector for a default cowshed, I prescribed the connector all according to the instructions, the sleeve sees the connector but when I try to connect it, my sleeve just flies two meters away , what could be the problem tell me
![fsScreen_2020_11_11_08_44_36](https://user-images.githubusercontent.com/71912030/98757667-9ea24780-23ff-11eb-892a-05a67a8a5b31.png)
![fsScreen_2020_11_11_08_44_50](https://user-images.githubusercontent.com/71912030/98757669-a06c0b00-23ff-11eb-9c1c-8e588d1a51c3.png)
![fsScreen_2020_11_11_08_51_43](https://user-images.githubusercontent.com/71912030/98757673-a06c0b00-23ff-11eb-9fe4-31db7da2d84e.png)

**Comment by stijnwop** [comment]
Hey,

As described in the documentation check your rootnode setup.

https://github.com/stijnwop/manureSystem/blob/master/docs/PLACEABLES.md#important
