### ISSUE TITLE
Hose not connet to anyting

### ISSUE THREAD

**Issue by markusa96** [stijnwop/manureSystem#132]
hello. i just got a problem with this mod, it work great on the map befor but sundetli it will not connet to any ting it ust jumps a way. is sayin i can right click but noting is happyning, i use a orginalt manuarspreader, with hose connteter on. pleas help. can send my log.

**Comment by jason0611** [comment]
Lumberjack-Mod in use? Then this will be the cause.

**Comment by markusa96** [comment]
Thanks, it whas that mod
