### ISSUE TITLE
Pump refuses to work

### ISSUE THREAD

**Issue by Killersnufferd** [stijnwop/manureSystem#14]
i have the zuhnhamer 18500 with hoses into a lake, i tried it with the stahlpump in between and without one but it refuses to pump after the first time of starting it.

**Comment by stijnwop** [comment]
1. What map?
2. Is the hose in the water deep enough
3. Did you open the manure flow on the standalone pump?

**Comment by Killersnufferd** [comment]
the hose is defenitely in deep enough, it isnt working on any of the pumps and slurry tanks and its on the map gemeinde Rade (a map wich some dude did a review of your mod on)

**Comment by Killersnufferd** [comment]
![Schermopname (47)](https://user-images.githubusercontent.com/62111756/76545106-7980c200-6489-11ea-9524-2cba365ff781.png)
![Schermopname (45)](https://user-images.githubusercontent.com/62111756/76545114-7be31c00-6489-11ea-81c0-3eb7afd0c983.png)
![Schermopname (49)](https://user-images.githubusercontent.com/62111756/76545124-7ede0c80-6489-11ea-95ba-14047f73c301.png)
![Schermopname (48)](https://user-images.githubusercontent.com/62111756/76545131-81406680-6489-11ea-834c-36183959ffb4.png)

**Comment by Killersnufferd** [comment]
it is in dutch but it doesnt say activate pump or tank anywhere

**Comment by stijnwop** [comment]
Ik geloof dat gemeinde Rade geen waterplane heeft ..

Dus dat werkt niet op die map.. probeer het maar eens met een standaard map om dit te bevestigen.

**Comment by Killersnufferd** [comment]
bereid om discord call te joinen maakt alles net wat gemakkelijker?

**Comment by Killersnufferd** [comment]
op rabe heb je denk ik gelijk met de waterplane, op de ravenport doet hij het namelijk wel. weet je toevallig uit je hoofd een versie van Rade die al een manure conector trigger op de ingebouwde lagoon bij de koeien heeft zitten?

**Comment by stijnwop** [comment]
Zo ver ik weet is er nog geen versie die voorbereid is..

Aangezien dit dus een map issue is sluit ik de issue.
