### ISSUE TITLE
Error when selling a attached slurry tanker that is connected to the Zunhammer FANT

### ISSUE THREAD

**Issue by JonasMC2004** [stijnwop/manureSystem#145]
If you sell a slurry tanker connected to the FANT, errors will occur.
[log.txt](https://github.com/stijnwop/manureSystem/files/5996276/log.txt)

**Comment by stijnwop** [comment]
Right good found, and solved it. ;)

**Comment by JonasMC2004** [comment]
It doesn't seam like it is fixed i just downloaded the newest github version but it still happens

**Comment by stijnwop** [comment]
Obviously as this fix is on the FANT and will be out as soon it's updated in the modhub.

**Comment by JonasMC2004** [comment]
Oh sorry I thought this is a Error of the manure system not the FANT

**Comment by stijnwop** [comment]
Yes, I should have mentioned it 👍 :D 

But it's solved nonetheless.
