### ISSUE TITLE
Only hoses apear in shop, no pumps etc.

### ISSUE THREAD

**Issue by thenono** [stijnwop/manureSystem#146]
Hey,

i've downloaded the manure systme and a compatible map. But in the shop category slurry i only see the hoses, the same goes for the fertilizer. Im not able to find the pumps or see them. I already reinstalled the game and removed other mods and tried it with the vanilla maps. Not Version of the manure system brings the pumps to the shop.

**Comment by KITT3000** [comment]
You mean this?
https://www.farming-simulator.com/mod.php?mod_id=155809&title=fs2019
https://www.farming-simulator.com/mod.php?mod_id=198879&title=fs2019
https://www.farming-simulator.com/mod.php?mod_id=155808&title=fs2019
