### ISSUE TITLE
Fillarmreciever does not work

### ISSUE THREAD

**Issue by JonasGHansen** [stijnwop/manureSystem#150]
Hello there - Im having trouble using fillarm on the first two, even tho they are supported, and the last one is standard.. works fine. log says nothing about any of them.
Docking works fine.

This one is made with the fillarmreciever, and are downloadable on modhub, but does not work. even when its full
![fsScreen_2021_03_07_17_16_56](https://user-images.githubusercontent.com/80212524/110246735-107f3d80-7f69-11eb-85fc-902cb58f1ee8.png)
This i've tried adding it myself, does not work either
![fsScreen_2021_03_07_17_17_06](https://user-images.githubusercontent.com/80212524/110246736-11b06a80-7f69-11eb-89a7-e730ce44f16a.png)
Standard one works.
![fsScreen_2021_03_07_17_17_36](https://user-images.githubusercontent.com/80212524/110246737-12490100-7f69-11eb-86bf-88a696797172.png)

**Comment by JonasGHansen** [comment]
Funnel/docking works fine... no problem (also on the other one)
![fsScreen_2021_03_07_17_23_41](https://user-images.githubusercontent.com/80212524/110246944-06117380-7f6a-11eb-9eb0-806f15a01d41.png)
But even with slurry in it, i cannot fill even tho im under plane.
![fsScreen_2021_03_07_17_24_39](https://user-images.githubusercontent.com/80212524/110246947-0742a080-7f6a-11eb-83bf-be8a6a04503b.png)

**Comment by stijnwop** [comment]
Did you read the part from the docs about checking the raycast line in F5 view mode, it's most likely pointing in the wrong direction.

**Comment by stijnwop** [comment]
Oh right, thought you where preparing the fillarm at first.
The containers most likely are not setup for the fillarm receivers.. check if those have the fillArmReceiver entry in the XML. I know for sure some containers from modhub don't have it added, even tho they mentioned 'manure system ready'.

Anyhow, this is not an issue for here.

**Comment by JonasGHansen** [comment]
Ehmm... As i said in text above, The containers already have the Receiver build in the XML... the first one actually was when i downloaded.. and tried adding on the 2nd one (1st and 2nd picture) from your guidance in docs...? But does not work.
The one on the first picture - Last marked line.
![image](https://user-images.githubusercontent.com/80212524/110253861-c740e500-7f8c-11eb-98c1-05cbc99ce19d.png)

**Comment by JonasGHansen** [comment]
But thanks alot for answering this fast :D Its an AWESOME mod... i really just want it to work :D

**Comment by JonasGHansen** [comment]
Hey, I dont know if u see my reply now, you have closed it, but both of
them do have the receiver in XML

Den søn. 7. mar. 2021 kl. 17.57 skrev Stijn Wopereis <
notifications@github.com>:

**Comment by JonasGHansen** [comment]
So far i can tell i cannot find any buffer container anywhere that works with the reciever?
