### ISSUE TITLE
Overload problem

### ISSUE THREAD

**Issue by agestar69** [stijnwop/manureSystem#153]
Hello, I have a problem. If I leave the Manure System out of the mods folder, I can overload it with R as normal.
If I use version 1.2, I cannot overload the barn without a hose. This is problematic because AutoDrive does not connect hoses. This was rehearsed at several loading points

**Comment by stijnwop** [comment]
When the Autodrive helper or course play helper is active the vanilla overload options should function.

It's indeed not visible when you try it yourself.

**Comment by agestar69** [comment]
Can't you somehow do both?

**Comment by stijnwop** [comment]
What's the point of manure system then?

**Comment by agestar69** [comment]
Yes, you are right.
