### ISSUE TITLE
limitedFillDirection not working properly

### ISSUE THREAD

**Issue by SgtRoyal** [stijnwop/manureSystem#154]
I tried to limit the fill direction of a fillarm with `imitedFillDirection="OUT"` but that will cause an error. 

```
2021-04-17 21:26 Error: Running LUA method 'loadSharedI3DFileFinished'.
2021-04-17 21:26 F:/Programme/FarmingSim/mods/FS19_manureSystem/src/vehicles/ManureSystemFillArm.lua:179: attempt to index global 'HoseSystemPumpMotor' (a nil value)
```

Line 179 ind the _ManureSystemFillArm.lua_ reads as following:

`fillArm.limitedFillDirection = limit:upper() == ManureSystemPumpMotor.PUMP_DIRECTION_IN_STR and ManureSystemPumpMotor.PUMP_DIRECTION_IN or HoseSystemPumpMotor.PUMP_DIRECTION_OUT`

changing **HoseSystemPumpMotor** to **ManureSystemPumpMotor** will resolve this problem.

Limiting the fill direction now works somewhat properly however the default direction is "IN" so as you start the game you can still use the fillarm to fill your trailer. After switching to "OUT" everything works fine, as you can't switch back to "IN".

**Comment by stijnwop** [comment]
Pushed a fix for both addressed isses
