### ISSUE TITLE
XML entry for "#isParkPlace"

### ISSUE THREAD

**Issue by plexten** [stijnwop/manureSystem#16]
Hello Wopster+Team great MOD,
short question, what is the XML entry for "#isParkPlace" to carry the hose on the barrel.

Translate deepl.com

**Comment by stijnwop** [comment]
```xml
<manureSystemConnectors>
        <connector type="COUPLING" isParkPlace="true" parkPlaceLength="3" createNode="true" position="-1.06 1.58 -3.4"/>
    </manureSystemConnectors>
```

Like the normal COUPLING entry.. but with the isParkPlace attribute.

**Comment by plexten** [comment]
Thanks for the quick answer, works great.
