### ISSUE TITLE
WTF is this

### ISSUE THREAD

**Issue by s4t4n** [stijnwop/manureSystem#162]
https://farming-simulator.com/mod.php?lang=de&country=de&mod_id=268216&title=fs2022

the zip file is just a png picture and a music video clip, no desription. 
and a virus destroys hdd's! 
WTF! A lawyer will sue for damages

**Comment by KITT3000** [comment]
XD

**Comment by derHaggie** [comment]
:-D

**Comment by stijnwop** [comment]
Look at the date and take a chill pill.
Have fun suing open source.
