### ISSUE TITLE
Basegame BGA dont work with Zunhammer yellow slurry trailers

### ISSUE THREAD

**Issue by KalifZerich** [stijnwop/manureSystem#166]
Just cant fill them up, with this green same issue
![fsScreen_2023_11_08_19_44_20](https://github.com/stijnwop/manureSystem/assets/132508316/9cb2ac2e-546b-41f5-9146-2a70b1edf3dc)

**Comment by JoPi1998** [comment]
These trailers don't have an own pump, that's why you can't fill them up.

**Comment by KalifZerich** [comment]
Thanks for reply, how can I use them now? They dont fill tru triiger now, thanks

**Comment by JoPi1998** [comment]
You can use the Stallkamp pump from ModHub (https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=281048). It's made for tanks without an own pump.

**Comment by KalifZerich** [comment]
WOW thanks, never seen that

**Comment by stijnwop** [comment]
Answer was given by JoPi.
