### ISSUE TITLE
Manure system

### ISSUE THREAD

**Issue by Michaelj15** [stijnwop/manureSystem#169]
Hello wopster,

Thanks for releasing the fs22 version :)
Unfortunately it didn't work for me,  i didn't get the left mouse trigger.
Could you give me a solution how to find the problem?
I know how it works from the Fs2019, but in Fs22 i can't get any help text in f1 menu and it doesn't connect.
The mod appears in the shop and i could buy the hoses. (i tested it with the vehicles in the main page on github).
I used a standard map with a new savegame. Also without any mods activated.

Thanks in advance!

**Comment by stijnwop** [comment]
Hi, strange..

Could you share the log file?

**Comment by Michaelj15** [comment]
Ofcourse, below attached. (savegame 2 Elmcreek is a blank savegame)
Side question, are you from the Netherlands?

[log.txt](https://github.com/stijnwop/manureSystem/files/13306624/log.txt)

**Comment by stijnwop** [comment]
The log seems to be very crowded with mods that are being loaded.. and god there a lots of callstacks going on from other mods. Please provide a clean log that clearly states only MS being loaded.

My advice would be to cleanup the mod folder first and reintroduce mods that are not causing that many issues.
And move forward from that. As this report very much implies you do have mod-conflicts.

Yes I am from the Netherlands.

**Comment by Michaelj15** [comment]
Ah lol, ik ook :) 
Ja dat klopt. Komt mede door een mod map waar ik nog aan het werk mee ben. 
Geven mods ook conflicten met manure mod als deze niet zijn geladen in de savegame, maar wel in de mod folder staan?

**Comment by JoPi1998** [comment]
If the mods are done well, there should be no conflict, if they are disabled on the savegame but still in mod folder.
To be safe it's recommended to remove all mods, except manure system, from your mod folder.

**Comment by Michaelj15** [comment]
I'm gonna try that last one. I have old but nice mods, they have a lot of errors and some lines I can't fix. The authors don't update it anymore. 
I will try to empty the mod folder and paste one by one back and see which makes the conflict.

**Comment by JoPi1998** [comment]
Some people have issues with manure system, if they use a 3rd person camera mod. Maybe it's the problem in your case, too.

**Comment by Michaelj15** [comment]
Ah thanks, gonna try that first. Have 3rd person also in the folder

**Comment by Bkp666** [comment]
Hi, I seem to have the same problem, mod loads fine, I can buy the hoses and the pump, but when I try to connect them, nothing happens(not getting the help text in the F1 box either)
I tested it and I think it is caused by the [PrecisionHands mod](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=265312&title=fs2022). Strange thing is, there are no errors in the log.

**Comment by s4t4n** [comment]
the 3rd person mod was it at me

**Comment by Michaelj15** [comment]
I tested all and the problem mods are indeed 3rd Person, Precision hands and Precision farming . I think i play the game without manure system and wait for an official release. Playing with 3rd Person and Precision farming is more fun for me. Never mind manure system is a fantastic upgrade for the game and i hope you guys or the other modders find a solution.

**Comment by s4t4n** [comment]
Precision Farming is working fine with ms, also the changed PF mod.
And ms is official at modhub ;)

**Comment by Michaelj15** [comment]
Mm strange, I cleared all mods out the folder and only pf en ms putted in. When I deleted pf it works fine 😬

**Comment by s4t4n** [comment]
really unusual.
Game is updated?

**Comment by stijnwop** [comment]
Ms was made compatible with PF, you sure you´re not running some modified version of it?

**Comment by Michaelj15** [comment]
No I didn't change any of the original files. Game is updated yesterday. Maybe a pdlc bug, but it's all from the original download channels

**Comment by Michaelj15** [comment]
Found the solution (i think). Deleted all dlc's, reset the keybindings and deleted the manure xml. 
Final test 😂
![image](https://github.com/stijnwop/manureSystem/assets/59195589/4e90de52-1ec8-419e-a606-660a363e1c01)

**Comment by stijnwop** [comment]
Right, issue list has been created and the issue has been described. Please contact the modders of 3rd person and precision hands cause they both have implementation issues causing all mods (not only MS) that depend on the same user code to be incompatible.
