### ISSUE TITLE
Hose is detaching and flies away when i try it connecting it to a valve

### ISSUE THREAD

**Issue by AgrarHub** [stijnwop/manureSystem#171]
Every time i try to connect a hose to a valve it just detaches and flies away.
There is nothing in the LOG sayong something.

Here is the xml from the Biogasplant:

<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<placeable type="productionPoint" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../shared/xml/schema/placeable.xsd">
    <storeData>
        <name>Thueringer_Hoehe_bga01_function</name>
        <functions>
            <function>$l10n_function_productionPoint</function>
        </functions>
        <image>$data/placeables/planET/bga250kw/store_bga250kw.png</image>
        <price>875000</price>
        <lifetime>1000</lifetime>
        <rotation>0</rotation>
        <brand>PLANET</brand>
        <species>placeable</species>
        <category>productionPoints</category>
        <brush>
            <type>placeable</type>
            <category>production</category>
            <tab>factories</tab>
        </brush>
        <vertexBufferMemoryUsage>3704064</vertexBufferMemoryUsage>
        <indexBufferMemoryUsage>912896</indexBufferMemoryUsage>
        <textureMemoryUsage>3801088</textureMemoryUsage>
        <instanceVertexBufferMemoryUsage>0</instanceVertexBufferMemoryUsage>
        <instanceIndexBufferMemoryUsage>0</instanceIndexBufferMemoryUsage>

        <storeIconRendering>
            <settings cameraXRot="-30" cameraYRot="-30" advancedBoundingBox="true"/>
        </storeIconRendering>
        <audioMemoryUsage>0</audioMemoryUsage>
    </storeData>

    <base>
        <filename>maps/mapUS/placeables/function/bga01/bga.i3d</filename>
        <canBeRenamed>true</canBeRenamed>
        <boughtWithFarmland>true</boughtWithFarmland>
    </base>

    <placement useRandomYRotation="false" useManualYRotation="true" >
        <testAreas>
            <testArea startNode="0>0|0" endNode="0>0|0|0" />
        </testAreas>

        <sounds>
            <place template="medImp" />
        </sounds>
    </placement>

    <clearAreas>
    </clearAreas>

    <leveling>
    </leveling>

    <indoorAreas>
    </indoorAreas>

    <tipOcclusionUpdateAreas>
        <tipOcclusionUpdateArea startNode="0>0|0" endNode="0>0|0|0" />
    </tipOcclusionUpdateAreas>

    <ai>
        <updateAreas>
            <updateArea startNode="0>0|0" endNode="0>0|0|0" />
        </updateAreas>
    </ai>

    <infoTrigger triggerNode="0>1"/>

    <triggerMarkers>
        <triggerMarker node="0>4|1|1"       filename="$data/shared/assets/marker/markerIcons.xml" id="UNLOAD" adjustToGround="false" />
        <triggerMarker node="0>4|0|1"               filename="$data/shared/assets/marker/markerIcons.xml" id="LOAD"   adjustToGround="true" />
        <triggerMarker node="0>4|3|0"             filename="$data/shared/assets/marker/markerIcons.xml" id="WRENCH" adjustToGround="false" />
    </triggerMarkers>

    <hotspots>
        <hotspot type="PRODUCTION_POINT" linkNode="0>2" teleportNode="0>3"/>
    </hotspots>

    <productionPoint>
        <productions sharedThroughputCapacity="false">
            <production id="biogas" name="$l10n_fillType_silage" cyclesPerHour="1" costsPerActiveHour="6.3">
                <inputs>
                    <input fillType="SILAGE" amount="2120" />
                </inputs>
                <outputs>
                    <output fillType="ELECTRICCHARGE" amount="1909" sellDirectly="true"/>
                    <output fillType="METHANE"        amount="1"    sellDirectly="true"/>
                    <output fillType="DIGESTATE"      amount="636" />
                </outputs>
            </production>
            <production id="biogasManure" name="$l10n_fillType_manure" cyclesPerHour="1" costsPerActiveHour="6.3">
                <inputs>
                    <input fillType="MANURE" amount="505" />
                </inputs>
                <outputs>
                    <output fillType="ELECTRICCHARGE" amount="455"  sellDirectly="true"/>
                    <output fillType="METHANE"        amount="1"    sellDirectly="true"/>
                    <output fillType="DIGESTATE"      amount="152" />
                </outputs>
            </production>
            <production id="biogasSugarbeetCut" name="$l10n_fillType_sugarBeetCut" cyclesPerHour="1" costsPerActiveHour="6.3">
                <inputs>
                    <input fillType="SUGARBEET_CUT" amount="253" />
                </inputs>
                <outputs>
                    <output fillType="ELECTRICCHARGE" amount="227"  sellDirectly="true"/>
                    <output fillType="METHANE"        amount="1"    sellDirectly="true"/>
                    <output fillType="DIGESTATE"      amount="76" />
                </outputs>
            </production>
        </productions>

        <sellingStation node="sellingStation" appearsOnStats="true" supportsExtension="true">

            <unloadTrigger exactFillRootNode="0>4|1|0"       fillTypes="SILAGE MANURE SUGARBEET_CUT" />
            <unloadTrigger fillTypes="SILAGE SUGARBEET_CUT">
                <baleTrigger triggerNode="0>4|1|2" />
            </unloadTrigger>
        </sellingStation>

        <loadingStation fillTypes="MANURE LIQUIDMANURE" supportsExtension="true">
            <loadTrigger triggerNode="0>4|0|2" fillTypes="DIGESTATE" aiNode="0>4|0|0"/>
        </loadingStation>

        <storage isExtension="false" fillLevelSyncThreshold="100">
            <capacity fillType="SILAGE"        capacity="76000" />
            <capacity fillType="MANURE"        capacity="18000" />
            <capacity fillType="SUGARBEET_CUT" capacity="9000" />
            <capacity fillType="DIGESTATE"     capacity="3900000" />

        </storage>

        <playerTrigger node="0>4|3" />

        <sounds>
            <idle template="dairyIdle" linkNode="0>4|1|1" outerRadius="50"/>
            <active template="dairyWork" linkNode="0>4|1|1" outerRadius="50"/>
        </sounds>
		
    </productionPoint>
	
	<manureSystem hasConnectors="true" />
	    <manureSystemConnectors>
            <connector type="COUPLING" node="5|0|2" />
        </manureSystemConnectors>

</placeable>

**Comment by stijnwop** [comment]
For history:
Add componentNode="PATH TO CLOSEST PHYSICS NODE" to the connector entry :)
