### ISSUE TITLE
Not working with Precision Hands mod enabled

### ISSUE THREAD

**Issue by RimePendragon** [stijnwop/manureSystem#175]
I can't attach hoses with the [Precision Hands](https://www.farming-simulator.com/mod.php?mod_id=265312) mod enabled. Which is a shame because I really like that mod.

**Comment by KITT3000** [comment]
https://github.com/stijnwop/manureSystem#known-conflicts

**Comment by stijnwop** [comment]
Known, as @KITT3000 posted.
Please contact the modder to fix their mod.

**Comment by RimePendragon** [comment]
I tried to contact the modder but can't find any contact info, only a old facebook page.
