### ISSUE TITLE
park connector - hose is hanging down

### ISSUE THREAD

**Issue by DrewCZ** [stijnwop/manureSystem#179]
Hi, please why this park connector doesn't work? 

definition: 
```
        <connector type="COUPLING" isParkPlace="true" parkPlaceLength="3" createNode="true" position="1.06 1.58 -3.4" startTransOffset="0 0.03 0.1" />
        <connector type="COUPLING" isParkPlace="true" parkPlaceLength="3" createNode="true" position="-1.06 1.58 -3.4" startTransOffset="0 0.03 0.1" />
```
same situation on both sides: 
![obrazek](https://github.com/stijnwop/manureSystem/assets/26751314/75801163-fb0d-42f6-a3b1-31c0a639df16)

also compared with your def:
<vehicle xml="data/vehicles/farmtech/supercis800/supercis800.xml"> 
but no mistake was found. 

thank you for your help

**Comment by stijnwop** [comment]
Please read the docs:
https://github.com/stijnwop/manureSystem/blob/master/docs/VEHICLES.md#setting-up-park-places

The definition you show is from FS19 and deprecated.

**Comment by DrewCZ** [comment]
Oh, my misunderstanding, sorry. I think that more than one length is optional and is possible to define one length in simple form as parameters. Well, corrected on my side. 
One question about deformers. You wrote: _The deformer node can be created like any other node..._
Is possible to connect the deformer to 0> node (reps. leave 'linkNode' undefined)? According to the docs, seems to be, but 
`<deformer createNode="true" position="1.06 1.68 0"/>`
seems to be generating a lua error.

**Comment by KITT3000** [comment]
@DrewCZ how else do you want to "attach" the deformer since linkNode is responsible for it because then it becomes the zero (base) position for your newly defined position

**Comment by DrewCZ** [comment]
everything clear, thank you for your help
