### ISSUE TITLE
Other Placeable Type for Husbandry

### ISSUE THREAD

**Issue by Chaosfamily1207** [stijnwop/manureSystem#183]
Hi Wopster, your instructions list the placeable types that can be used! My stables all have their own placeable type! Will the system still work? My stables have the type cowHusbandrySolar or pigHusbandrySolar. Could I change this myself somewhere so that it works without having to change my type?

**Comment by JoPi1998** [comment]
It works, if your placeable type has the spec "husbandry" (this should be the case for all husbandries, as it is the main spec for it).

**Comment by Chaosfamily1207** [comment]
Thanks for the quick reply.
