### ISSUE TITLE
can't open debug

### ISSUE THREAD

**Issue by Friendlyx** [stijnwop/manureSystem#194]
when I type i msToggleDebug the command is unkown. Any help?

**Comment by KITT3000** [comment]
Did you activate "cheats" in the game?

**Comment by Friendlyx** [comment]
what do you mean? the console is on. I can do all gs Commands and Courseply commands

**Comment by KITT3000** [comment]
By default, you only have 1/10th of the active commands in the game, paaramter "-cheats" adds 90% of commands to you

**Comment by Friendlyx** [comment]
worked! thanks
