### ISSUE TITLE
Add 5m Slurry hose

### ISSUE THREAD

**Issue by moep0710** [stijnwop/manureSystem#20]
Hi,

I would like to have a 5m slurry hose (because my 3m looked so short on my slurry spreader), so I build it myself. Since it's not possible to add files in github, I will upload it here. If you are interested in, just add it to your next version. I also included the updated moddesc and updated translation xmls.

[Slurryhose5m.zip](https://github.com/stijnwop/manureSystem/files/4331488/Slurryhose5m.zip)

**Comment by stijnwop** [comment]
Cool! But..
Highly doubt your setup will work smooth with the curren´t code, also it´s lacking some setups.. like the catmull length and component setup.
Will have to see if I ever plan to add a longer hose.. bug fixing has more prio atm. 😄
