### ISSUE TITLE
Cant extract digestate from PlanET BGA 99kw

### ISSUE THREAD

**Issue by Altrac00** [stijnwop/manureSystem#203]
Hi.
The mod is awesome.

I can not extract digestate from the PlanET BGA 99kw using a Manure System compatilbe tanker.
The hose and tanker connect and works in the port next to the blue output icon, but they pumps the slurry previuly added to the BGA, not the digestate. Using a tanker with no manuresystem suport will works as intended.

The BGA is installed in Haut-Beyleron in the parcel 38.

In the screenshot you can see the tanker extracted some slurry.
![20240518085800_1](https://github.com/stijnwop/manureSystem/assets/96493479/da5fe410-1fbf-4c12-b81d-7dda1c440541)

**Comment by JoPi1998** [comment]
Is there a hose connected to the slurry connector while you try to pump digestate from the BGA?
If so, try it again after disconnecting the hose from the slurry connector.

**Comment by Altrac00** [comment]
Yes. Just at this moment I returned to post my "discovery"

Thank you so much.
