### ISSUE TITLE
No 2 connector types possible in one trailer

### ISSUE THREAD

**Issue by FarmerAndy** [stijnwop/manureSystem#21]
I tried to find two connector guys in a trailer
Coupling and CouplingFertilizer. And I noticed a strange behaviour, which has the following effect in the game the CouplingFertilizer hose is connected to the 1 node of the Coupling, although this should not work at all.  

Here a small example:
```
<manureSystemConnectors>
		<connector type="COUPLING" node="16|0"/>
		<connector type="COUPLING" node="16|1"/>
		<connector type="COUPLINGFERTILIZER" node="16|2" />
		<connector type="COUPLING" node="16|3" isParkPlace="true"/>
</manureSystemConnectors>
```
The Fertilizer hose is connected to the first Connector Node with these settings although it is a Manure connection. If you exclude the first two coupling nodes in the XML. Then the Fertilizer hose works. The scenario can also be reversed. If you put the type: CouplingFertilizer in the tag <manureSystemConnectors> in the first place then only the type of the CouplingFertilizer is used and the LiquidManure tubing is connected to this connector.

**Comment by stijnwop** [comment]
Hey, could u please update with the latest source from GitHub and check again.

Fixed an issue similar to this earlier today.

**Comment by stijnwop** [comment]
Also this one @FarmerAndy :smiley:

**Comment by stijnwop** [comment]
Another reminder @FarmerAndy 😄
