### ISSUE TITLE
Hoses can't be connected to each other.

### ISSUE THREAD

**Issue by Merrlin** [stijnwop/manureSystem#23]
Hi,
Ive found an Issue with Commit f71705f. Manure Hoses cant connect to each other with this version. 
If i try to connect them together (RMB) nothing happens and the console just says:
[MS Error]: Corrupted savegame, the loaded connector type does not match the hose connector type!
The save was completely new (not even saved) just with my testing mods like CP and EDC. If u need a logfile say something.

Greets

**Comment by stijnwop** [comment]
Oh god, let me fix that haha

**Comment by stijnwop** [comment]
Fixed.

**Comment by Merrlin** [comment]
Can confirm. Bug fixed.
