### ISSUE TITLE
Overloading from vehicle to vehicle with manureFlowAnimation Empty Bug?

### ISSUE THREAD

**Issue by FarmerAndy** [stijnwop/manureSystem#28]
Found a problem.

If you want to overload by hose from one trailer to the other and use a manureFlow animation on both trailers, the FillLevel will become less as soon as you turn on a tap without the pump being turned on. 
But the connected trailer remains empty and you want to fill it. So you get no content.  And the content runs into nothing.

If you have both taps open, it works without any errors.

**GERMAN:**

Habe ein Problem festgestellt.

Wenn man per Schlauch von einen Trailer in den anderen Überladen will und nutzt eine manureFlowAnimation an beiden Trailern, dann wird das FillLevel weniger sobald man einen Hahn aufdreht ohne das die Pumpe angeschalten ist. 
Dabei bleibt aber der angeschlossenen Trailer leer den man befüllen möchte. Man bekommt also kein Inhalt dazu.  Und der Inhalt läuft ins Nichts.

Wenn man beide Hähne offen hat, funktioniert es aber Fehlerfrei.

**Comment by stijnwop** [comment]
Good catch.. just pushed a fix.

**Comment by stijnwop** [comment]
@FarmerAndy any time to test the fix?

**Comment by FarmerAndy** [comment]
Yes, I tested it and it worked great. But only in singleplayer as it is in multiplayer I can't say.  

Thanks also for the service you are really fast with fixes ^^

**Comment by stijnwop** [comment]
Alright, nice.. can you update me later on the mp? :smile:

**Comment by FarmerAndy** [comment]
Yeah, I can do that if I remember.

**Comment by stijnwop** [comment]
Little reminder. @FarmerAndy 😄
