### ISSUE TITLE
FlowControlAnimation bei bgaplaceable wirft Fehler aus

### ISSUE THREAD

**Issue by Patar95** [stijnwop/manureSystem#30]
Hallo,

habe mich heute damit beschäftigt, das manureSystem für unsere MP-Truppe in die Geiselsberg einzubauen. Funktioniert auch prima, nur bei den BGA's bekomme ich immer einen Fehler, wenn ich die manureFlowAnimation mit drinen lasse. Der Fehler kommt aus der HosePlayer.lua Zeile 123.

Er verschluckt sich wohl irgendwo in Zeile 114-116, weil er denkt, die BGA wäre ein Fahrzeug? Jedenfalls gibt es in Zeile 123 die Funktion getAnimationTime nicht.

Die Animationen sind richtig initialisiert, da die lockAnimation wunderbar funktioniert, und auch die manureFlowAnimation bei den Husbandries funktioniert, nur bei den beiden BGA's gibts dieses Problem. 

Gruß Thomas

**Comment by Patar95** [comment]
Sorry for writing in german. I just saw an other german issue so I thought you were german... Hope you can translate it....

**Comment by stijnwop** [comment]
Hey, can you attach the log file for me?

**Comment by Patar95** [comment]
Sorry, i dont have an log file with that error at the moment.

It's very close to:

...scr/hose/HosePlayer.lua (line 123) attemp to call function "getAnimationTime" (a nil value)

As I told you, he can't find that funktion on that table "vehicle" in line 123.

If you really want to see the original log error, I have to recreate that in our map...

**Comment by stijnwop** [comment]
@Patar95 I pushed a fix, can you please test and confirm?

**Comment by Patar95** [comment]
Hey, just tried it now. I can connect the hose now, but if I want to open the valve on the connector, there is an other error now:

2020-03-16 20:00 Error: Running LUA method 'update'.
2020-03-16 20:00 D:/Users/Documents/My Games/FarmingSimulator2019/mods/FS19_manureSystem/src/hose/HosePlayer.lua:309: attempt to call method 'getIsAnimationPlaying' (a nil value)

Thank you for your fast reaction.

**Comment by stijnwop** [comment]
Ah, duh dumb me.

Pushed a fix for that too.

**Comment by Patar95** [comment]
works fine now :)   Thank you very much!
