### ISSUE TITLE
Manure System

### ISSUE THREAD

**Issue by FarmerMike87** [stijnwop/manureSystem#31]
Hallo zusammen ich hab versuch das System in einen Kuhstall einzubauen erhalte aber nur diesen LUA call stack und der stall lässt sich nicht plazieren.

Können sie mir helfen wo liegt mein Problem

2020-03-15 21:44 C:/Users/Mike/Documents/My Games/FarmingSimulator2019/mods/FS19_German_Cowshed/germanCowstable.i3d (81.48 ms)
2020-03-15 21:44   Error: Failed to find child 0 from node liquidManureTrigger, only 0 childs given
2020-03-15 21:44 LUA call stack:
2020-03-15 21:44   dataS/scripts/i3d/I3DUtil.lua (20) : printCallstack
2020-03-15 21:44   dataS/scripts/i3d/I3DUtil.lua (88) : checkChildIndex
2020-03-15 21:44   dataS/scripts/triggers/LoadTrigger.lua (35) : indexToObject
2020-03-15 21:44   dataS/scripts/animals/AnimalHusbandryModules/HusbandryModuleLiquidManure.lua (60) : load
2020-03-15 21:44   =C:/Users/Mike/Documents/My Games/FarmingSimulator2019/mods/FS19_manureSystem/src/misc/ManureSystemHusbandryModuleLiquidManure.lua (77) : superFunc
2020-03-15 21:44   dataS/scripts/animals/AnimalHusbandry.lua (113) : load
2020-03-15 21:44   dataS/scripts/animals/AnimalHusbandry.lua (79) : loadModules
2020-03-15 21:44   dataS/scripts/utils/PlacementUtil.lua (320) : load
2020-03-15 21:44   dataS/scripts/gui/PlacementScreenController.lua (172) : loadPlaceable
2020-03-15 21:44   dataS/scripts/gui/PlacementScreen.lua (191) : activate
2020-03-15 21:44   dataS/scripts/gui/elements/GuiElement.lua (721) : raiseCallback
2020-03-15 21:44   dataS/scripts/gui/base/Gui.lua (751) : onOpen
2020-03-15 21:44   dataS/scripts/gui/base/Gui.lua (773) : changeScreen
2020-03-15 21:44   dataS/scripts/gui/elements/FrameElement.lua (182) : changeScreenCallback
2020-03-15 21:44   dataS/scripts/gui/ShopMenu.lua (438) : changeScreen
2020-03-15 21:44   dataS/scripts/gui/ShopController.lua (200) : callback
2020-03-15 21:44   dataS/scripts/gui/ShopController.lua (605) : startPlacementModeCallback
2020-03-15 21:44   dataS/scripts/gui/ShopMenu.lua (688) : buy
2020-03-15 21:44   dataS/scripts/gui/ShopItemsFrame.lua (425) : notifyActivatedDisplayItemCallback
2020-03-15 21:44   dataS/scripts/gui/elements/ListElement.lua (556) : raiseCallback
2020-03-15 21:44   dataS/scripts/gui/elements/ListElement.lua (537) : notifyDoubleClick
2020-03-15 21:44   dataS/scripts/gui/elements/ListElement.lua (651) : onMouseUp
2020-03-15 21:44   dataS/scripts/gui/elements/GuiElement.lua (616) : mouseEvent
2020-03-15 21:44   dataS/scripts/gui/elements/GuiElement.lua (616) : mouseEvent
2020-03-15 21:44   dataS/scripts/gui/elements/GuiElement.lua (616) : mouseEvent
2020-03-15 21:44   dataS/scripts/gui/elements/GuiElement.lua (616) : mouseEvent
2020-03-15 21:44   dataS/scripts/gui/elements/GuiElement.lua (616) : mouseEvent
2020-03-15 21:44   dataS/scripts/gui/elements/GuiElement.lua (616) : mouseEvent
2020-03-15 21:44   dataS/scripts/gui/base/Gui.lua (561) : mouseEvent
2020-03-15 21:44   dataS/scripts/main.lua (1767) : mouseEvent
2020-03-15 21:44   Error: Index not found: 0
2020-03-15 21:44 Error: LoadTrigger could not load trigger. Check the user attribute 'triggerNode'
2020-03-15 21:44 LUA call stack:
2020-03-15 21:44   dataS/scripts/triggers/LoadTrigger.lua (44) : printCallstack
2020-03-15 21:44   dataS/scripts/animals/AnimalHusbandryModules/HusbandryModuleLiquidManure.lua (60) : load
2020-03-15 21:44   =C:/Users/Mike/Documents/My Games/FarmingSimulator2019/mods/FS19_manureSystem/src/misc/ManureSystemHusbandryModuleLiquidManure.lua (77) : superFunc
2020-03-15 21:44   dataS/scripts/animals/AnimalHusbandry.lua (113) : load
2020-03-15 21:44   dataS/scripts/animals/AnimalHusbandry.lua (79) : loadModules
2020-03-15 21:44   dataS/scripts/utils/PlacementUtil.lua (320) : load
2020-03-15 21:44   dataS/scripts/gui/PlacementScreenController.lua (172) : loadPlaceable
2020-03-15 21:44   dataS/scripts/gui/PlacementScreen.lua (191) : activate
2020-03-15 21:44   dataS/scripts/gui/elements/GuiElement.lua (721) : raiseCallback
2020-03-15 21:44   dataS/scripts/gui/base/Gui.lua (751) : onOpen
2020-03-15 21:44   dataS/scripts/gui/base/Gui.lua (773) : changeScreen
2020-03-15 21:44   dataS/scripts/gui/elements/FrameElement.lua (182) : changeScreenCallback
2020-03-15 21:44   dataS/scripts/gui/ShopMenu.lua (438) : changeScreen
2020-03-15 21:44   dataS/scripts/gui/ShopController.lua (200) : callback
2020-03-15 21:44   dataS/scripts/gui/ShopController.lua (605) : startPlacementModeCallback
2020-03-15 21:44   dataS/scripts/gui/ShopMenu.lua (688) : buy
2020-03-15 21:44   dataS/scripts/gui/ShopItemsFrame.lua (425) : notifyActivatedDisplayItemCallback
2020-03-15 21:44   dataS/scripts/gui/elements/ListElement.lua (556) : raiseCallback
2020-03-15 21:44   dataS/scripts/gui/elements/ListElement.lua (537) : notifyDoubleClick
2020-03-15 21:44   dataS/scripts/gui/elements/ListElement.lua (651) : onMouseUp
2020-03-15 21:44   dataS/scripts/gui/elements/GuiElement.lua (616) : mouseEvent
2020-03-15 21:44   dataS/scripts/gui/elements/GuiElement.lua (616) : mouseEvent
2020-03-15 21:44   dataS/scripts/gui/elements/GuiElement.lua (616) : mouseEvent
2020-03-15 21:44   dataS/scripts/gui/elements/GuiElement.lua (616) : mouseEvent
2020-03-15 21:44   dataS/scripts/gui/elements/GuiElement.lua (616) : mouseEvent
2020-03-15 21:44   dataS/scripts/gui/elements/GuiElement.lua (616) : mouseEvent
2020-03-15 21:44   dataS/scripts/gui/base/Gui.lua (561) : mouseEvent
2020-03-15 21:44   dataS/scripts/main.lua (1767) : mouseEvent
2020-03-15 21:44 Error: Running LUA method 'mouseEvent'.
2020-03-15 21:44 dataS/scripts/triggers/LoadTrigger.lua(153) : bad argument #1 to 'pairs' (table expected, got nil)

### <?xml version="1.0" encoding="utf-8" standalone="no" ?>
<placeable>
    <storeData>
        <name>
        <en>German Cow Barn</en>
        <de>Deutscher Kuhstall</de>
        </name>
        <image>store_germanCowstable.png</image>
        <price>550000</price>
        <functions>
            <function>$l10n_function_animalPenCow</function>
        </functions>
        <lifetime>1000</lifetime>
        <dailyUpkeep>400</dailyUpkeep>
        <rotation>0</rotation>
        <brand>Lizard</brand>
        <species>placeable</species>
        <category>animalpens</category>
        <vertexBufferMemoryUsage>4266516</vertexBufferMemoryUsage>
        <indexBufferMemoryUsage>671670</indexBufferMemoryUsage>
        <textureMemoryUsage>77512128</textureMemoryUsage>
        <instanceVertexBufferMemoryUsage>0</instanceVertexBufferMemoryUsage>
        <instanceIndexBufferMemoryUsage>0</instanceIndexBufferMemoryUsage>
    </storeData>

    <placeableType>husbandry</placeableType>
    <filename>germanCowstable.i3d</filename>
    <placement testSizeX="53.0" testSizeZ="78.0" sizeX="53" sizeZ="78" useRandomYRotation="false" useManualYRotation="true" placementRotationSnapAngle="90" placementPositionSnapSize="0.5" placementPositionSnapOffset="0.25"/>

    <clearAreas>
        <clearArea startNode="0|11|0" widthNode="0|11|0|0" heightNode="0|11|0|1"/>
    </clearAreas>

    <leveling requireLeveling="true" maxSmoothDistance="10" maxSlope="75" maxEdgeAngle="30">
        <levelAreas>
            <levelArea startNode="0|12|0" widthNode="0|12|0|0" heightNode="0|12|0|1" groundType="grass"/>
            <levelArea startNode="0|12|1" widthNode="0|12|1|0" heightNode="0|12|1|1" groundType="gravel"/>
            <levelArea startNode="0|12|2" widthNode="0|12|2|0" heightNode="0|12|2|1" groundType="gravel"/>
            <levelArea startNode="0|12|3" widthNode="0|12|3|0" heightNode="0|12|3|1" groundType="gravel"/>
            <levelArea startNode="0|12|4" widthNode="0|12|4|0" heightNode="0|12|4|1" groundType="gravel"/>
            <levelArea startNode="0|12|5" widthNode="0|12|5|0" heightNode="0|12|5|1" groundType="gravel"/>
        </levelAreas>
        <rampAreas> 
            <rampArea maxSlope="75" rootNode="0|13|0" startNode="0|13|0" widthNode="0|13|0|0" heightNode="0|13|0|1" groundType="grass"/>
            <rampArea maxSlope="75" rootNode="0|13|1" startNode="0|13|1" widthNode="0|13|1|0" heightNode="0|13|1|1" groundType="grass"/>
            <rampArea maxSlope="75" rootNode="0|13|2" startNode="0|13|2" widthNode="0|13|2|0" heightNode="0|13|2|1" groundType="grass"/>
            <rampArea maxSlope="75" rootNode="0|13|3" startNode="0|13|3" widthNode="0|13|3|0" heightNode="0|13|3|1" groundType="grass"/>
        </rampAreas>
    </leveling>

    <foliageAreas>
        <foliageArea fruitType="grass" rootNode="0|14|0" />
    </foliageAreas>

      <seasons>
        <maskAreas>
            <maskArea startNode="0|17|0" widthNode="0|17|0|0" heightNode="0|17|0|1" />
            <maskArea startNode="0|17|1" widthNode="0|17|1|0" heightNode="0|17|1|1" />
            <maskArea startNode="0|17|2" widthNode="0|17|2|0" heightNode="0|17|2|1" />
            <maskArea startNode="0|17|3" widthNode="0|17|3|0" heightNode="0|17|3|1" />
            <maskArea startNode="0|17|4" widthNode="0|17|4|0" heightNode="0|17|4|1" />
        </maskAreas>
            
        <admirers>
            <snowAdmirer node="0|17|5"/>
        </admirers>
    </seasons>

    <triggerMarkers>
        <triggerMarker node="0|15" />
    </triggerMarkers>

    <hotspots>
        <hotspot name="Cow barn" fullName="$l10n_animals_cowPasture" imageName="COW_BARN" hidable="true" category="CATEGORY_TRIGGERS" />
    </hotspots>

    <manureSystemConnectors>
		<connector type="COUPLING" linkNode="0|3|3" createNode="true" position="3.134 0.142 0.497" rotation="-1.167 -74.074 -0.503" />
	</manureSystemConnectors>

    

    <animatedObjects>
        <animatedObject saveId="door_01" >
            <animation duration="7">
                <part node="0|1|0|0|1">
                    <keyFrame time="0.0" rotation="0 0 0"/>
                    <keyFrame time="0.5" rotation="0 -175 0"/>
                </part>
                <part node="0|1|0|0|2">
                    <keyFrame time="0.0" rotation="0 0 0"/>
                    <keyFrame time="0.5" rotation="0 181 0"/>
                </part>
                <part node="0|1|0|0|4">
                    <keyFrame time="0.5" rotation="0 0 0"/>
                    <keyFrame time="1.0" rotation="0 -175 0"/>
                </part>
                <part node="0|1|0|0|3">
                    <keyFrame time="0.5" rotation="0 0 0"/>
                    <keyFrame time="1.0" rotation="0 181 0"/>
                </part>
            </animation>
            <controls triggerNode="0|1|0|0|0" posAction="ACTIVATE_HANDTOOL" posText="action_openGate" negText="action_closeGate" />
            <sounds>
                <moving file="$data/sounds/prefab/gate/gate_loop.wav" loops="0" linkNode="0|1|0|0|0" volume="0.8" radius="25" innerRadius="3" fadeOut="0.25"/>
                <posEnd file="$data/sounds/prefab/gate/gate_opened.wav" linkNode="0|1|0|0|0" volume="0.8" radius="25" innerRadius="3" />
                <negEnd file="$data/sounds/prefab/gate/gate_closed.wav" linkNode="0|1|0|0|0" volume="0.8" radius="25" innerRadius="3" />
            </sounds>
        </animatedObject>
        <animatedObject saveId="door_02" >
            <animation duration="7">
                <part node="0|1|0|1|1">
                    <keyFrame time="0.0" rotation="0 0 0"/>
                    <keyFrame time="0.5" rotation="0 -181 0"/>
                </part>
                <part node="0|1|0|1|2">
                    <keyFrame time="0.0" rotation="0 0 0"/>
                    <keyFrame time="0.5" rotation="0 180 0"/>
                </part>
                <part node="0|1|0|1|4">
                    <keyFrame time="0.5" rotation="0 0 0"/>
                    <keyFrame time="1.0" rotation="0 -181 0"/>
                </part>
                <part node="0|1|0|1|3">
                    <keyFrame time="0.5" rotation="0 0 0"/>
                    <keyFrame time="1.0" rotation="0 180 0"/>
                </part>
            </animation>
            <controls triggerNode="0|1|0|1|0" posAction="ACTIVATE_HANDTOOL" posText="action_openGate" negText="action_closeGate" />
            <sounds>
                <moving file="$data/sounds/prefab/gate/gate_loop.wav" loops="0" linkNode="0|1|0|1|0" volume="0.8" radius="25" innerRadius="3" fadeOut="0.25"/>
                <posEnd file="$data/sounds/prefab/gate/gate_opened.wav" linkNode="0|1|0|1|0" volume="0.8" radius="25" innerRadius="3" />
                <negEnd file="$data/sounds/prefab/gate/gate_closed.wav" linkNode="0|1|0|1|0" volume="0.8" radius="25" innerRadius="3" />
            </sounds>
        </animatedObject>
        <animatedObject saveId="door_03" >
            <animation duration="7">
                <part node="0|1|0|2|1">
                    <keyFrame time="0.0" rotation="0 -180 0"/>
                    <keyFrame time="1.0" rotation="0 0 0"/>
                </part>
                <part node="0|1|0|2|2">
                    <keyFrame time="0.0" rotation="0 180 0"/>
                    <keyFrame time="1.0" rotation="0 0 0"/>
                </part>
            </animation>
            <controls triggerNode="0|1|0|2|0" posAction="ACTIVATE_HANDTOOL" posText="action_closeGate" negText="action_openGate" />
            <sounds>
                <moving file="$data/sounds/prefab/gate/gate_loop.wav" loops="0" linkNode="0|1|0|2|0" volume="0.8" radius="25" innerRadius="3" fadeOut="0.25"/>
                <posEnd file="$data/sounds/prefab/gate/gate_opened.wav" linkNode="0|1|0|2|0" volume="0.8" radius="25" innerRadius="3" />
                <negEnd file="$data/sounds/prefab/gate/gate_closed.wav" linkNode="0|1|0|2|0" volume="0.8" radius="25" innerRadius="3" />
            </sounds>
        </animatedObject>
        <animatedObject saveId="door_04" >
            <animation duration="7">
                <part node="0|1|0|3|1">
                    <keyFrame time="0.0" rotation="0 0 0"/>
                    <keyFrame time="1.0" rotation="0 -180 0"/>
                </part>
                <part node="0|1|0|3|2">
                    <keyFrame time="0.0" rotation="0 0 0"/>
                    <keyFrame time="1.0" rotation="0 180 0"/>
                </part>
            </animation>
            <controls triggerNode="0|1|0|3|0" posAction="ACTIVATE_HANDTOOL" posText="action_openGate" negText="action_closeGate" />
            <sounds>
                <moving file="$data/sounds/prefab/gate/gate_loop.wav" loops="0" linkNode="0|1|0|3|0" volume="0.8" radius="25" innerRadius="3" fadeOut="0.25"/>
                <posEnd file="$data/sounds/prefab/gate/gate_opened.wav" linkNode="0|1|0|3|0" volume="0.8" radius="25" innerRadius="3" />
                <negEnd file="$data/sounds/prefab/gate/gate_closed.wav" linkNode="0|1|0|3|0" volume="0.8" radius="25" innerRadius="3" />
            </sounds>
        </animatedObject>
        <animatedObject saveId="door_05" >
            <animation duration="1.5">
                <part node="0|1|0|4|1">
                    <keyFrame time="0.0" rotation="0 0 0"/>
                    <keyFrame time="1.0" rotation="0 -99 0"/>
                </part>
            </animation>
            <controls triggerNode="0|1|0|4|0" posAction="ACTIVATE_HANDTOOL" posText="action_openGate" negText="action_closeGate" />
            <sounds>
                <moving file="$data/sounds/prefab/gate/gate_loop.wav" loops="0" linkNode="0|1|0|4|0" volume="0.8" radius="25" innerRadius="3" fadeOut="0.25"/>
                <posEnd file="$data/sounds/prefab/gate/gate_opened.wav" linkNode="0|1|0|4|0" volume="0.8" radius="25" innerRadius="3" />
                <negEnd file="$data/sounds/prefab/gate/gate_closed.wav" linkNode="0|1|0|4|0" volume="0.8" radius="25" innerRadius="3" />
            </sounds>
        </animatedObject>
        <animatedObject saveId="net" >
            <animation duration="8">
                <part node="0|1|0|5|1">
                    <keyFrame time="0.0" scale="1 1 1"/>
                    <keyFrame time="1.0" scale="1 0.002 1"/>
                </part>
            </animation>
            <controls triggerNode="0|1|0|5|0" posAction="ACTIVATE_HANDTOOL" posText="input_NET_CLICK" negText="input_NET_CLICK" />
        </animatedObject>
        <animatedObject saveId="gate_01" >
            <animation duration="1.5">
                <part node="0|2|0">
                    <keyFrame time="0.0" rotation="0 0 0"/>
                    <keyFrame time="1.0" rotation="0 -120 0"/>
                </part>
                <part node="0|2|1">
                    <keyFrame time="0.0" rotation="0 0 0"/>
                    <keyFrame time="1.0" rotation="0 120 0"/>
                </part>
            </animation>
            <controls triggerNode="0|16" posAction="ACTIVATE_HANDTOOL" posText="action_openGate" negText="action_closeGate" />
            <sounds>
                <moving file="$data/sounds/prefab/gate/gate_loop.wav" loops="0" linkNode="0|16" volume="0.8" radius="25" innerRadius="3" fadeOut="0.25"/>
                <posEnd file="$data/sounds/prefab/gate/gate_opened.wav" linkNode="0|16" volume="0.8" radius="25" innerRadius="3" />
                <negEnd file="$data/sounds/prefab/gate/gate_closed.wav" linkNode="0|16" volume="0.8" radius="25" innerRadius="3" />
            </sounds>
        </animatedObject>
        <animatedObject saveId="lights" >
            <animation duration="0.5">
                <part node="0|1|0|6|0|0">
                    <keyFrame time="0.0" visibility="false"/>
                    <keyFrame time="0.4" visibility="true"/>
                </part>
                <part node="0|1|0|6|1|0">
                    <keyFrame time="0.4" visibility="false"/>
                    <keyFrame time="0.6" visibility="true"/>
                </part>
                <part node="0|1|0|6|2|0">
                    <keyFrame time="0.6" visibility="false"/>
                    <keyFrame time="0.8" visibility="true"/>
                </part>
                <part node="0|1|0|6|3|0">
                    <keyFrame time="0.8" visibility="false"/>
                    <keyFrame time="1.0" visibility="true"/>
                </part>
                <part node="0|1|0|6|4|0">
                    <keyFrame time="0.8" visibility="false"/>
                    <keyFrame time="1.0" visibility="true"/>
                </part>
                <part node="0|1|0|6|5|0">
                    <keyFrame time="0.6" visibility="false"/>
                    <keyFrame time="0.8" visibility="true"/>
                </part>
                <part node="0|1|0|6|6|0">
                    <keyFrame time="0.4" visibility="false"/>
                    <keyFrame time="0.6" visibility="true"/>
                </part>
                <part node="0|1|0|6|7|0">
                    <keyFrame time="0.0" visibility="false"/>
                    <keyFrame time="0.4" visibility="true"/>
                </part>
            </animation>
            <controls triggerNode="0|1|0|6|8" posAction="ACTIVATE_HANDTOOL" posText="action_lightSwitchON" negText="action_lightSwitchOFF" />
        </animatedObject>
    </animatedObjects>

    <husbandry saveId="Animals_COW" hasStatistics="false">
        <modules>
            <module name="animals">
                <config type="COW" navmeshNode="0|9" animalLoadTriggerNode="0|0" maxNumAnimals="100" husbandryFileName="$dataS/character/cowAnimalHusbandry.xml" placementRaycastDistance="2.0" carryingCapacity="50" rideableDeliveryStartNode="0|7|0" rideableDeliveryWidthNode="0|7|0|0" rideableDeliveryHeightNode="0|7|0|1" />
            </module>
            <module name="food">
                <config node="0|6|0" exactFillRootNode="0" baleTriggerNode="3" animalPlacesNode="1" >
                    <fillPlane node="0|6|1" minY="-0.413" maxY="0.114" colorChange="true" />
                </config>
            </module>
            <module name="water">
                <config node="0|10|0|19|0" exactFillRootNode="0" fillTypes="WATER" acceptedToolTypes="undefined trailer">
                    <fillPlane node="0|10|0|19|1" minY="0.06" maxY="0.275" colorChange="true" />
                </config>
            </module>
            <module name="liquidManure">
                <config node="0|3|0" fillTypes="LIQUIDMANURE" triggerNode="0">
                    <fillPlane node="0|3|1" minY="0" maxY="0.011" />
                </config>
            </module>
            <module name="manure">
                <config startNode="0|4|0|0" widthNode="0|4|0|0|0" heightNode="0|4|0|0|1" fillType="MANURE"/>
            </module>
            <module name="foodSpillage">
                <config fillType="SILAGE">
                    <area startNode="0|6|0|2|0" widthNode="0|6|0|2|0|0" heightNode="0|6|0|2|0|1" />
                </config>
            </module>
            <module name="milk">
                <config node="0|8" fillTypes="MILK" triggerNode="0" />
            </module>
            <module name="straw">
                <config node="0|5" exactFillRootNode="0" baleTriggerNode="2" fillTypes="STRAW">
                    <fillPlane node="0|5|1" minY="-0.27" maxY="-0.169" colorChange="false" />
                </config>
            </module>
        </modules>
        <placementRaycast distance="2" />
    </husbandry>

    <tipOcclusionUpdateArea sizeX="53" sizeZ="93" />

</placeable>

https://abload.de/img/unbenannt8jj2q.png

LG Mike

**Comment by stijnwop** [comment]
Really simple.. the index you defined is invalid.

**Comment by FarmerMike87** [comment]
Which index do I have to use ?????

LG Mike

**Comment by stijnwop** [comment]
You're asking me like I am some kind of fortune teller :smile: 

I have no idea about what object you're preparing nor the environment. Lookup the node `liquidManureTrigger` mentioned in the log.. and what index to use.

**Comment by FarmerMike87** [comment]
Es handelt sich um dieses Objekt 👍 

LG Mike
