### ISSUE TITLE
Rotate Parts of sharedSets

### ISSUE THREAD

**Issue by N1Jul1an** [stijnwop/manureSystem#32]
Adding the possibility to rotate separate Parts of an sharedSet.

I thougt about a tag adding like that:
```
<sharedSet createNode="true" position="1.19 0.849 2.799" rotation="-90 0 -26" placeholderNode="0>0|24">
                <connector type="CONNECTOR_1" />
                <valve type="8INCH_BRASS"/>
                <handle type="HANDLE_NEW" />
            </sharedSet>
```
adding just a `rotation="-90 0 0"`  tag to all types that can be loaded, so a new tag would look like this
`<connector type="CONNECTOR_1" rotation="-90 0 0"/>`

Kind regards <3

**Comment by stijnwop** [comment]
@N1Jul1an please test.

**Comment by CCL1106** [comment]
works fine for me
