### ISSUE TITLE
Adding faq to helpers in game like AD example

### ISSUE THREAD

**Issue by PromGames** [stijnwop/manureSystem#33]
I think that you can add the explanations in game about manure system like Stephan made code in Autodrive to get that help in game. 

Maybe is possible for you to setup as helper and connect with translations files where translations for different language could be set

**Comment by stijnwop** [comment]
I am actually thinking about giving pump warnings again like i did in 17

So it warns you about closed manure flows, or empty source objects etc.

**Comment by PromGames** [comment]
What I mean is use a code to create the helpers like this:

`<text name="ad_helpCategory_1"							text="AutoDrive" />
		
		<text name="ad_helpTitle_01"							text="AD - Introduction" />
		<text name="ad_helpText_01_01"							text="AutoDrive is a multipurpose tool to let your tractors navigate autonomously through the world of Farming Simulator." />
		<text name="ad_helpText_01_02"							text="The backbone is an interconnected network of recorded points and defined destinations. For some maps, an initial network is provided with the mod. On most maps you will have to record everything yourself or import a network from another user (see import/export below)." />
		<text name="ad_helpText_01_03"							text="Provided all destinations are properly connected to the network, AutoDrive navigates much like your typical navigation system in your car, by calculating the shortest route to the destination.So it is important to ensure that all points are connected to the network. If AutoDrive detects a disconnected point, it is marked with an ‚X‘ and should be removed or connected by the player." />
		`

This going together with this code in register.Lua

`g_helpLineManager:loadFromXML(Utils.getFilename("helpLine.xml", AutoDrive.directory))`

This based on the following xml File

`<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<helpLines>
    <category title="$l10n_ad_helpCategory_1">
        <page title="$l10n_ad_helpTitle_01">
            <item type="text" value="$l10n_ad_helpText_01_01"/>
            <item type="text" value="$l10n_ad_helpText_01_02"/>
            <item type="text" value="$l10n_ad_helpText_01_03"/>
        </page>
        <page title="$l10n_ad_helpTitle_02">
            <item type="text" value="$l10n_ad_helpText_02_01"/>
        </page>
        <page title="$l10n_ad_helpTitle_03">
            <item type="text" value="$l10n_ad_helpText_03_01"/>
            <item type="text" value="$l10n_ad_helpText_03_02"/>
            <item type="text" value="$l10n_ad_helpText_03_03"/>
        </page>
        <page title="$l10n_ad_helpTitle_04">
            <item type="text" value="$l10n_ad_helpText_04_01"/>
            <item type="text" value="$l10n_ad_helpText_04_02"/>
            <item type="text" value="$l10n_ad_helpText_04_03"/>
            <item type="text" value="$l10n_ad_helpText_04_04"/>
            <item type="text" value="$l10n_ad_helpText_04_05"/>
        </page>
        <page title="$l10n_ad_helpTitle_05">
            <item type="text" value="$l10n_ad_helpText_05_01"/>
            <item type="text" value="$l10n_ad_helpText_05_02"/>
            <item type="text" value="$l10n_ad_helpText_05_03"/>
            <item type="text" value="$l10n_ad_helpText_05_04"/>
        </page>
        <page title="$l10n_ad_helpTitle_06">
            <item type="text" value="$l10n_ad_helpText_06_01"/>
            <item type="text" value="$l10n_ad_helpText_06_02"/>
            <item type="text" value="$l10n_ad_helpText_06_03"/>
        </page>
        <page title="$l10n_ad_helpTitle_07">
            <item type="text" value="$l10n_ad_helpText_07_01"/>
            <item type="text" value="$l10n_ad_helpText_07_02"/>
            <item type="text" value="$l10n_ad_helpText_07_03"/>
            <item type="text" value="$l10n_ad_helpText_07_04"/>
            <item type="text" value="$l10n_ad_helpText_07_05"/>
        </page>
        <page title="$l10n_ad_helpTitle_08">
            <item type="text" value="$l10n_ad_helpText_08_01"/>
            <item type="text" value="$l10n_ad_helpText_08_02"/>
            <item type="text" value="$l10n_ad_helpText_08_03"/>
            <item type="text" value="$l10n_ad_helpText_08_04"/>
            <item type="text" value="$l10n_ad_helpText_08_05"/>
        </page>
        <page title="$l10n_ad_helpTitle_09">
            <item type="text" value="$l10n_ad_helpText_09_01"/>
        </page>
        <page title="$l10n_ad_helpTitle_10">
            <item type="text" value="$l10n_ad_helpText_10_01"/>
            <item type="text" value="$l10n_ad_helpText_10_02"/>
            <item type="text" value="$l10n_ad_helpText_10_03"/>
        </page>
        <page title="$l10n_ad_helpTitle_11">
            <item type="text" value="$l10n_ad_helpText_11_01"/>
        </page>
        <page title="$l10n_ad_helpTitle_12">
            <item type="text" value="$l10n_ad_helpText_12_01"/>
            <item type="text" value="$l10n_ad_helpText_12_02"/>
            <item type="text" value="$l10n_ad_helpText_12_03"/>
        </page>
        <page title="$l10n_ad_helpTitle_13">
            <item type="text" value="$l10n_ad_helpText_13_01"/>
            <item type="text" value="$l10n_ad_helpText_13_02"/>
            <item type="text" value="$l10n_ad_helpText_13_03"/>
            <item type="text" value="$l10n_ad_helpText_13_04"/>
            <item type="text" value="$l10n_ad_helpText_13_05"/>
        </page>
    </category>
</helpLines>`

**Comment by stijnwop** [comment]
Yeah totally got what you mean, problem is that people don't read it anyway.. so don't see the value to add that (as this is not a console mod at all, that's the only reason such a helpline thing is useful as we did with Seasons.) Same goes for the readme or any mod description, they don't read.

I have some experience with mods.. most people just ask questions without reading into anything cause that's the easiest way for them.
