### ISSUE TITLE
src/hose/Hose.lua:176: attempt to call method 'getName' (a nil value)`

### ISSUE THREAD

**Issue by PromGames** [stijnwop/manureSystem#35]
I am loosing my savegames as corrupt due to Manure system when I try to connect to the hose, but not every time only when connecting some vehicles. I have restored the savegame already four times.

¿Maybe is because i changed the manure system mod to anew version and there are older vehicles in the vehicles xml configured with previuos versions?

`2020-03-17 19:59 Game saved successfully.
2020-03-17 20:16 Error: Running LUA method 'onSaveStartComplete'.
2020-03-17 20:16 D:/My Games Old/FarmingSimulator2019/ModsHot2k19/FS19_manureSystem/src/hose/Hose.lua:176: attempt to call method 'getName' (a nil value)`

After this error happens all save process goes to hell and disappear many of the files form the savegame.
Before Crash
![image](https://user-images.githubusercontent.com/9979168/76909942-f4dcdc00-68ac-11ea-87c7-d948b7862e98.png)

After Crash
![image](https://user-images.githubusercontent.com/9979168/76909874-c959f180-68ac-11ea-8efa-80181c5bd743.png)

Complete Log

[log.txt](https://github.com/stijnwop/manureSystem/files/4346207/log.txt)

**Comment by stijnwop** [comment]
To what object did you connect that results into that error? Can you try to connect to a single object and save till the error appears?

Cause this is related to a specific object.. that does not have the method.

Sure this should not happen.. will look at it as soon as possible when I get your response.

**Comment by PromGames** [comment]
I will make some test now that save game will be ok and check all connections I Did. Busy today and tomorrow for work, I am in corona virus vaccine research team but I will try to get some time to take a look.

**Comment by stijnwop** [comment]
Sure no rush take your time! You got more important stuff todo.

Did add a check in the meantime that should prevent your savegame going corrupt.

**Comment by PromGames** [comment]
Everything OK now. I could not get the error anymore

![image](https://user-images.githubusercontent.com/9979168/77226171-816def80-6b76-11ea-97bf-070d07bcde38.png)
