### ISSUE TITLE
Triggers for liquid pallets

### ISSUE THREAD

**Issue by Nico-CH74** [stijnwop/manureSystem#36]
Hallo thank you and good job with this mod.

But the Global Company's SeedMaker (for example) is now broken

it is not possible to unload the fertilizer in its trigger. I assume that it is no longer possible to use the triggers for packaged liquid products.
Many warehouses and factories are supposed to be scripted to work again, and it won’t happen any time soon.
Could you create some tool that allows you to unload in a default trigger?
Thank you.

**Comment by atledreier** [comment]
I've run into this issue too. Any news on a solution?

**Comment by Irving-75** [comment]
Hello, I have a similar issue, the trigger in the shelf storage mod doesn0t work anymore and worse, I can't deactivate manure system because my savegame won't start, what can I do?

**Comment by stijnwop** [comment]
@Irving-75 #80 

@Nico-CH74 Same as in #80 .. it's the hardcoded check they do in the pallet trigger.

GC_UnloadingTrigger.lua -> line 432.

There check needs to be a bit more flexible.. e.g. `object.typeName:lower():find("pallet") works already.

There's no way around that for me besides removing manure system support on those pallets.

**Comment by stijnwop** [comment]
@atledreier 
@Nico-CH74 

Issue has been resolved by Kevin:
https://github.com/Ls-Modcompany/FS19_GlobalCompany/commit/b3aa7a332daea0c96c1f387a3a6d2c430d77ce77

You can update it there or wait for the next (pre)release.

**Comment by stijnwop** [comment]
Closing due to their modhub update/release.
