### ISSUE TITLE
If the manureSystem is active, automatic loading in courseplay doesn`t work anymore

### ISSUE THREAD

**Issue by Flashmaster23** [stijnwop/manureSystem#37]
Hi,
if the manureSystem is active, the automated loading with courseplay isn`t working anymore. This affects all trigger (Water, Silo, Fertilizer etc.) on mod-maps and the default map.
If the trailer is at the trigger and you enter the vehicle, the loading process starts.
If the manureSystem is disabled, the automated loading works fine.
Mayby you can contact the developer of coureplay to find a fix for this problem?
Thanks.

**Comment by Merrlin** [comment]
Wich Version of CP are you using?  Maybe Logfile would help too.
You can also report bugs to CP via
https://github.com/Courseplay/courseplay/issues

**Comment by Flashmaster23** [comment]
Hi,
I tested the following CP Versions:
v6.01.00397
v6.01.00396
v6.01.00395
v6.01.00394
v6.01.00390

[log.txt](https://github.com/stijnwop/manureSystem/files/4355378/log.txt)

**Comment by Merrlin** [comment]
Well, that sounds like a Task for @tensuko

**Comment by Flashmaster23** [comment]
I have an answer from Tensuko. It seemed, that the manureSystem need a hose attached at all triggers. But you can`t attach a hose at a silo trigger. Maybe you could add a filter or something that the mod affects only the manure trigger?

**Comment by Tensuko** [comment]
@stijnwop I think the solution is to allow all AI Drivers to still fill up manure without the hose attatched and only deactivate it for manual use.

**Comment by stijnwop** [comment]
Hi, @Tensuko whats the easiest way to detect on the vehicle is the AI driver is active/running?

**Comment by Tensuko** [comment]
Ehm, the easiest way is to ask @pvaiko ^^
But it would be interesting if @Stephan-S have similar Issues ?

**Comment by Stephan-S** [comment]
vehicle.spec_aivehicle.isActive

**Comment by stijnwop** [comment]
Yeah was more referring to CP or AD respectively and not the vanilla AI.

Thanks guys, will have a look

**Comment by stijnwop** [comment]
Fixed.

**Comment by stijnwop** [comment]
Noone confirming this?

**Comment by Tensuko** [comment]
Oh I am sry Wopster, it is fixed ofc, thanks again for your work.

**Comment by stijnwop** [comment]
Awesome thanks :)
