### ISSUE TITLE
ANNABURGER

### ISSUE THREAD

**Issue by kapatyh** [stijnwop/manureSystem#38]
in the screenshots, the ANNABURGER barrel works , but it doesn't work in the game .
![screenshot1](https://user-images.githubusercontent.com/59476246/77077223-c0852f00-6a16-11ea-8b1a-620df6619362.jpg)

**Comment by kapatyh** [comment]
And is it possible to make the hose longer ?

**Comment by stijnwop** [comment]
Yes grab the non extension side of the hose and walk to the extension side of a different hose.

Of course the Annaburger does not work as that mod has not received the updated yet to be compatible with the manure system.

Please be patient.
