### ISSUE TITLE
Change 'Attach Hose' to 'Store Hose' when parking

### ISSUE THREAD

**Issue by dziuch** [stijnwop/manureSystem#40]
When parking a hose on a rack on a vehicle could you change the 'Attach Hose' prompt to 'Store Hose'? Some of the rack triggers are close to the connectors and quite a few times I was fiddling with the hose trying to make it to connect, only for it to detach and park itself on a rack.

**Comment by stijnwop** [comment]
Great suggestion, will see what I can do

**Comment by stijnwop** [comment]
Added, please test @dziuch.

**Comment by dziuch** [comment]
Yep. Looks OK. Thanks. :)
