### ISSUE TITLE
Pump won't activate

### ISSUE THREAD

**Issue by isaacalex95** [stijnwop/manureSystem#41]
The hoses are connected, the manure flows are open, I have a nurse tank (Garant FRC) connected to the Stallkamp Pump which is then connected to the Abbey 2500R by 4D Modding. It was working yesterday but has since stopped pumping the slurry

**Comment by stijnwop** [comment]
You do need to pump from the stallkamp pump.. and make sure the flow is open on that pump too.

You can't pump from the stallkamp with a tanker obviously.

**Comment by isaacalex95** [comment]
I was trying to pump from the Stallkamp. It still wasn't pumping anything. It was working last night, saved it and quit and came on this morning for it to not work. No new mods or any other changes have been made.

**Comment by stijnwop** [comment]
Alright, so what do I have todo in order to reproduce this? The reproduceable steps.. log?

I am still no fortune teller.. sadly.

**Comment by isaacalex95** [comment]
ok, so I just tried it with a different tractor powering the pump, I think it could be an issue with mod tractors
