### ISSUE TITLE
Hose connector disappears

### ISSUE THREAD

**Issue by JonasPa967** [stijnwop/manureSystem#44]
Error: Running LUA method 'update'.
2020-03-24 07:28 D:/home/sid_600964/farmingSim_2019/profile/mods/FS19_manureSystem/src/hose/Hose.lua:740: attempt to index local 'connector' (a nil value)
we get this error on the dedi server, if we leave a hose connected to an animalstable, after a restart

**Comment by stijnwop** [comment]
Hey, can you update to the GitHub version first.. and re-test. This has been fixed weeks ago.

**Comment by stijnwop** [comment]
@JonasPa967 please test with the latest version.. and close the issue when solved.

**Comment by JonasPa967** [comment]
Hey, sry for the delayed response.
I have tested with the latest version and at the moment everything works fine.
thx for your help/support
