### ISSUE TITLE
Placeable / Connector / tube flows away when should be connected

### ISSUE THREAD

**Issue by jonaslinhose** [stijnwop/manureSystem#49]
Hello, sorry for my englisch... i do my very best :)

I would insert the ManueSystem to a FS19_Organic_pigsty_Placeable_V1_9.
I used your Documentatin in GitHub and there are no errors in the log (index should be ok).
But wenn i test it ingame (giants standard map) the tube flows away when i used the right button to connect the tube with the "transform" group.

This is the entry of my XML:
	<manureSystemConnectors>
		<connector type="COUPLING" node="0|3|2"/>
    </manureSystemConnectors>

I do the same with another barn (Milchhof by Eribus), there it works fine.

**Comment by stijnwop** [comment]
Hey did you read the documentation?
https://github.com/stijnwop/manureSystem/blob/master/docs/PLACEABLES.md#important

**Comment by jonaslinhose** [comment]
wow... sorry... read the fucking manual ... shame one me :) 

forget this stupid entry and thank you for this grade mod.
