### ISSUE TITLE
Pumping to/from the lagoon doesn't stop when you detach the hose

### ISSUE THREAD

**Issue by dziuch** [stijnwop/manureSystem#5]
Hello.

I found a small issue: the pumping to/from the [lagoon](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=155810&title=fs2019) doesn't stop when you detach the hose from the tanker. Doesn't matter if it's directly or through the [pump](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=155809&title=fs2019).

It works correctly when pumping between two tankers.

Platform: PC
FS19 Version: 1.5.1.0

No other mods loaded except for:
Manure System (1.0.0.0)
Manure System Lagoon (1.0.0.0)
Stallkamp Pump (1.0.0.0)
Zunhammer Tripod Hopper (1.0.0.0)
[Easy Development Controls](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=138864&title=fs2019) (1.0.0.0)

**Comment by stijnwop** [comment]
Jup thats true, like IRL your pump won't stop when you detach the hoses

**Comment by dziuch** [comment]
I mean the tank/lagoon continues to fill/empty after you detach the hose.

**Comment by stijnwop** [comment]
Mmm, i need to check

**Comment by stijnwop** [comment]
I can't confirm ..

When you detach but keep the manure flow open on your tanker it will continue to empty the tankers as the flow is open.

Make sure to close the flow first on both sides.

**Comment by dziuch** [comment]
Ok. I made a video showing the issue: https://youtu.be/I0dKjRm4rDA
In the video:
1. after attaching the hose and starting pumping I detach the hose from the tanker - the slurry keeps flowing to the lagoon
2. I detach the hose and drive off and then start the pump - the slurry keeps flowing to the lagoon

> When you detach but keep the manure flow open on your tanker it will continue to empty the tankers as the flow is open.

So you're saying it's intentional? I think it'll confuse the heck out of players.


You can see in the video by Farmer Klein: https://youtu.be/T2t1wPEyF-g?t=2272 he stumbles upon a similar issue when pumping fertilizer.

**Comment by stijnwop** [comment]
Ah, now I see it's a issue with those connectors that don't have animation.

Will fix.

**Comment by stijnwop** [comment]
@dziuch Can you confirm?

**Comment by dziuch** [comment]
Is there an updated lagoon mod, because the one that I've put down has disappeared and it's not in the shop either. Like, the lagoon mod doesn't detect that the manureSystem mod is on - and it's definitely on, I can buy the hoses in the shop. I also made sure both mods are enabled.
