### ISSUE TITLE
Problem Mit dem Güllesystem 

### ISSUE THREAD

**Issue by FarmerMike87** [stijnwop/manureSystem#50]
Wo liegt hier das Problem das letzte was ich gekauft habe waren die Schläuche, die Pumpe und zuvor die Ställe
[log.txt](https://github.com/stijnwop/manureSystem/files/4394343/log.txt)

Das ist der Stall: https://ls-modcompany.com/filebase/file/467-hot-animals/
Das is das Güllelager: https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=157884&title=fs2019

LG Mike

**Comment by stijnwop** [comment]
Are you using the modhub or GitHub version?

**Comment by FarmerMike87** [comment]
Ich benutze die Modhub version, hab jetzt die von GitHub geladen und der Fehler is weg.

**Comment by FarmerMike87** [comment]
Fehler besteht weiterhin, hab einen stall verkauft und dann hatte ich den gleichen fehler wieder, konnte den gülleschlauch greifen mich dann aber anschließend nicht mehr bewegen.

[log.txt](https://github.com/stijnwop/manureSystem/files/4396932/log.txt)

Der andere Fehler entstand als ich zwischen güllelager und stall gülle umpumpen wollten.
