### ISSUE TITLE
Gülle System funktioniert nicht

### ISSUE THREAD

**Issue by GigaGerrit** [stijnwop/manureSystem#56]
Hallo habe eine Frage: Weiß jemand warum das Güllesystem bei mir nicht funktioniert?? Ich habe die Schläuche, Global Company und Andockstationen, kann aber einfach die Schläuche trotz fester Tastenbelegung nicht ankoppeln.Also weder an andere Schläuche noch an andere Gebäude/ Güllefässer. Auch bei anderen Tastenbelegungen klappt es nicht. Weiß jemand warum, und was man tun kann? Würde mich über eine Antwort freuen.

**Comment by Floowy** [comment]
Schläuche ankoppeln mit rechter Maustaste, an Gebäuden bzw. Anschlüssen muss das manure system verbaut sein, entweder in direkt in der Karte wenn es sich um Ingame Gebäude handelt oder im jeweiligen Mod wenn es Placeabels sind

**Comment by GigaGerrit** [comment]
Ich war mir 100 prozentig sicher, dass ich das versucht habe! Habe ich aber anscheinend nicht:( ! Danke für die Info!

**Comment by stijnwop** [comment]
So this is resolved?

**Comment by Floowy** [comment]
Seems like, as I understand Gerrits message. Think can be closed
