### ISSUE TITLE
mixer issue in multiplayergame

### ISSUE THREAD

**Issue by EicherKiger** [stijnwop/manureSystem#57]
We  have a problem with the mixer installed in the lagoon isnt working in our MP game. Is there any solution already found?

**Comment by stijnwop** [comment]
A bit more context please..

With the github version or modhub? Game patch?
When does it happen? 

Steps to reproduce would be great.

**Comment by EicherKiger** [comment]
Sure, sorry

We are using the modhub version on the latest patch and are playing on a dedicated server.

The problem is that the mixer doesn't decrease the thickness of the digestate stored in the lagoon even if its turned on for 24 hours.

**Comment by bgo1973** [comment]
Found out that it can be solved by doing a little change in the xml.
Original:
Row 45:             <animationNode node="2|0" rotSpeed="-2700" rotAxis="1" turnOnFadeTime="2" turnOffFadeTime="5"/>
needs to be:
            <animationNode node="2|0" rotSpeed="+2700" rotAxis="1" turnOnFadeTime="2" turnOffFadeTime="5"/>

**Comment by AndyMaas** [comment]
Schalte da mich mal mit ein 
Da bgo und ich zusammen dran gesetzt haben 
Und muss dazu sagen das es in Singleplayer funktioniert nur auf den dedi server nicht 
Hoste ich selber ein Multiplayergame funktioniert der mixer wieder

**Comment by stijnwop** [comment]
Changing animation node has nothing todo with decreasing thickness.. it's just for the visual propeller down in the lagoon.

But had it confirmed already and will look into it.

**Comment by AndyMaas** [comment]
Hmm es ist mir aufgefallen wo ich das + vorgesetzt habe die manureplane sich erst dann bewegt wenn der mixer eingeschaltet wird 
Und mit den - sich bewegt wenn er abgeschaltet ist und erst wo ich das +vorgesetzt habe ist die gülledicke von der Prozentzahl runter gegangen 
Nur auf den dedi server funktioniert es nicht 
Denn dachte echt jetzt hab ich das Problem behoben und kann endlich gülle fahren 
Aber wenn es 30 Minuten dauert bis 35000 Liter in fass gepumt sind macht es nicht wirklich viel Spaß

**Comment by stijnwop** [comment]
Like I said.. the animated nodes have nothing todo with the movement of the plane or the mixing efficiency. That's just for visuals.. so its more likely a coincidence

**Comment by bgo1973** [comment]
@stijnwop It seemed that this change solved the issue in SP and self hosted MP. On dedi it still won't work. But as you recognized that issue you will know what to do. Thx btw. for that awesome mod. It really sets the experience to another level. Great job.

**Comment by flo5488** [comment]
we have the same error, the mixer works in the SP ...

Unfortunately not in the MP.
Manure system is available in the latest version of the Github.

**Comment by Snickers125** [comment]
> 
> 
> Changing animation node has nothing todo with decreasing thickness.. it's just for the visual propeller down in the lagoon.
> 
> But had it confirmed already and will look into it.

**Comment by dehjvg** [comment]
we goit the same isseue on our dedicated server the tickness is going up but activating the mixer does not decrease it (running latest version manuresystem of github) i can not find any errors in the logs

**Comment by stijnwop** [comment]
At what thickness is the lagoon?

**Comment by dehjvg** [comment]
thikness is 36% at the moment in the lagoon

**Comment by AndyMaas** [comment]
Also wir hatte schon die gülledicke auf 100% und sie ging auf den Server nicht mehr runter und wo ich genau das gleiche savegame in ls19 selber gehostet habe ging sie runter und in seasons bei 560 Kühen brauchen wir die Lagune

**Comment by stijnwop** [comment]
The little mixer blade is running?

**Comment by dehjvg** [comment]
yes it is

**Comment by stijnwop** [comment]
Alright, fixed the issue.

Please test. :)

**Comment by dehjvg** [comment]
tested it and thickness is going down now so its fixed

**Comment by flo5488** [comment]
only that the animation of the fill plane is still there when the mixer is off.
If you activate the mixer with R, the fill plane stands still. on a multiplayer game on Dedi server.
