### ISSUE TITLE
Automatic fill from SGT Pump to Samson Manure Barrel

### ISSUE THREAD

**Issue by rednaz01** [stijnwop/manureSystem#58]
Hello, First i would to say my english is bad.
i hope you understand it.

In this Afternoon i try to make the SGT Fillerarm Manure System ready.and the Samson pgII42 too.

It works with the manure Barrel everythings fine...the Fillerarm and the Hoses from SGT Fillerarm to Manure Barrel.
But only the SGT Fillerarm sucks the Manure i have to test a Capacity from 3000 Liters after this 3000 Liters the Pump dont stop but the manure Barrel is empty again..

The SGT Fillerarm is a Manure Barrel in the XML und when i Try to change in Frontdock is it the same Problem.
______________________________________
<manureSystem hasConnectors="true" hasPumpMotor="true" hasFillArm="true"/>
	
	<manureSystemPumpMotor useStandalone="true" litersPerSecond="250" toReachMaxEfficiencyTime="1000">
    <sounds>
        <pump template="SLURRY_02">
            <pitch indoor="0.85" outdoor="0.75"/>
        </pump>
    </sounds>
    </manureSystemPumpMotor>
	
    <manureSystemFillArm node="armNode" needsDockingCollision="true"/>
	
	<manureSystemFillArmReceiver fillVolumeIndex="1"/>
	
	
		
	<manureSystemConnectors>
		<connector type="COUPLING" createNode="true" position="0.011 0.959 3.932" rotation="20 0 0" />
		<connector type="COUPLING" isParkPlace="true" createNode="true" position="X Y Z" />
	</manureSystemConnectors>
__________________________
This is from the xml.
How can I do that fill the SGT and the Manure Barrel?
Greets Christian

**Comment by stijnwop** [comment]
`useStandalone` is no entry for the pump motor.. it's `isStandalone`.

Please check the documentations.. carefully.
