### ISSUE TITLE
Gülle System mit Contractor Mod kombinieren ?

### ISSUE THREAD

**Issue by Jaggermanjanson** [stijnwop/manureSystem#59]
Servus . 
Hat jemand den Contractor Mod  Gülle System ready gemacht und kann mir ne kurze Zusammenfassung geben wie das geht bzw geht das überhaupt da man ja mehrere "Charaktere" auf einmal hat ? Das sind zwei wundervolle Mods die ich gerne kombinieren möchte da ich viel Wert auf Realität lege . Habe Probleme die offizielle Anleitung zu verstehen konnte mich da noch nicht richtig reinfuchsen.
MfG Jagger

**Comment by stijnwop** [comment]
Did you even try the new GitHub update? This issue has been fixed weeks ago ^^

**Comment by Jaggermanjanson** [comment]
Oh pardon I didn't know that.  Loaded the mod from Modhub a week ago but I'm happy to hear that😍

**Comment by stijnwop** [comment]
https://github.com/stijnwop/manureSystem/releases/tag/1.0.9.0

Did a pre-release here.

**Comment by Jaggermanjanson** [comment]
Thank you 👍🏻
