### ISSUE TITLE
Güllelagune mixer funktioniert wohl nicht richtig 

### ISSUE THREAD

**Issue by AndyMaas** [stijnwop/manureSystem#62]
Hallo mir ist aufgefallen das die güllelagune nicht  richtig funktioniert denn der mixer läuft schon seit heute morgen bis jetzt durchgehend durch und es tut sich nichts an der gülledicke 
Und mir ist aufgefallen das die manureplane i der Nähe von mixer sich bewegt wenn der abgeschaltet ist und sobald man in einschalten ist die plane still

**Comment by stijnwop** [comment]
Duplicate of #57 .. we continue on that issue.
