### ISSUE TITLE
LUA call stack bei deutschem Kuhstall ausm ModHub

### ISSUE THREAD

**Issue by FarmerMike87** [stijnwop/manureSystem#64]
Ich häng mich hier mal mit dran 1zu1 der gleiche Fehler....
Hab diesen Stall im spiel gekauft, und ab dann war mit aufheben des Schlauches keine Bewegung mehr möglich ; https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=153232&title=fs2019

PS: Nutze die Version hier von GitHub.

Log im Anhang.
[log.txt](https://github.com/stijnwop/manureSystem/files/4420120/log.txt)

LG Mike

**Comment by AntondeBeuker** [comment]
Hallo FarmerMike87

Ich denke, wir haben den gleichen Fehler, aber es ist so, dass der Fehler bei mir erst besteht, wenn ich den Stall verkauf.
Nachherr habe ich der in-game kuhstall ausprobiert in eine neues spiel und hatte der gleiche fehler.
Ist das bei Dir auch so?

Grüße Anton

**Comment by FarmerMike87** [comment]
Ich hab den Fehler nur wenn ich nen Stall kauf hat ich auch bei den Hot_animals weis nicht wieso, verkauft hab ich ihn noch nicht wieder. 
Neues Savegame hab ich noch nicht getestet. 

Mach ich bei gelegenheit mal :)

**Comment by Snickers125** [comment]
Also Ich kann das bisher so nicht mit dem Stall aus dem Hub mit der GitHubversion reproduzieren.

**Comment by AntondeBeuker** [comment]
Kaufe einen Kuhstall und einen Schlauch.
Verkaufe den Kuhstall.
Wenn Sie dann den Schlauch aufheben, sollten Sie in der Lage sein, den Fehler aus dem Log zu reproduzieren

**Comment by Snickers125** [comment]
So selling the cowbarn with a connected hose?

**Comment by AntondeBeuker** [comment]
no you can leave the hose at the shop, doesn't need to be connected

**Comment by Snickers125** [comment]
> CONFIRMED

**Comment by stijnwop** [comment]
Fixed the issue.
