### ISSUE TITLE
problem mit der anbindung

### ISSUE THREAD

**Issue by TRLPmarkus** [stijnwop/manureSystem#66]
![fsScreen_2020_04_03_21_07_33](https://user-images.githubusercontent.com/55022079/78397177-14843c00-75f1-11ea-9065-35aa3f5be941.png)

wie auf dem bild zu sehen bekommen wir ein problem mit dem anbinden des schlauches wir haben nach anleitung angebaut

**Comment by TRLPmarkus** [comment]
![güllenlageraufbau](https://user-images.githubusercontent.com/55022079/78422061-e2102880-765c-11ea-9248-b4a013b6846b.png)

mein aufbau des lagerss ist so aufgebaut wie es auf dem bild zu sehen ist weis jetzt need was du meinst 

so die xml https://filehorst.de/d/dDyEcoFx  dazu

**Comment by Floowy** [comment]
Er meint das du beim manureconnectors mal einen rootNode reinschreiben sollst.
Quasi <manureSystemConnectors rootNode="1|1|2">
...
</manureSystemConnectors>
Sofern der 1|1|2 ein rigidBody ist sollte das passen bei dir

**Comment by TRLPmarkus** [comment]
also muss ich da auf  rigidBody gehen wenn ich dich jetzt richtig verstehe

**Comment by Floowy** [comment]
> also muss ich da auf rigidBody gehen wenn ich dich jetzt richtig verstehe

nein, du sollst nur schauen ob der 1|1|2 ein rigidBody ist, sonst musst du den rootNode entsprechend anpassen. Sorry auffem Handy hatte es den Beitrag etwas verwurstelt

**Comment by TRLPmarkus** [comment]
verstehe jetzt nicht wo ich das eintragen muss

**Comment by Floowy** [comment]
> verstehe jetzt nicht wo ich das eintragen muss

in der XML deines Güllelagers
'<manureSystemConnectors rootNode="1|1|2|0">
        <connector type="coupling" node="1|1|2|1" lockAnimationIndex="1" manureFlowAnimationIndex="2"/>
    </manureSystemConnectors>

**Comment by TRLPmarkus** [comment]
so hhabe ich es drin stehen 

 <manureSystemStorage hasMixer="true" mixPerSecond="150">
        <fillPlane node="1|2" planeMinY="-5.02" planeMaxY="0.027" detectionNode="1|3"/>
        <storage node="0" fillTypeCategories="slurryTank" capacityPerFillType="1718000"/>
        <trigger node="1|4"/>		
		<animationNodes>		
            <animationNode node="2|0" rotSpeed="-2700" rotAxis="1" turnOnFadeTime="2" turnOffFadeTime="5"/>
		</animationNodes>
        <sounds>
            <mix template="FORAGE_WAGON_01" linkNode="2"/>
        </sounds>
    </manureSystemStorage>

    <manureSystemConnectors>
        <connector type="coupling" node="1|1|2|1" lockAnimationIndex="1" manureFlowAnimationIndex="2"/>
    </manureSystemConnectors>

**Comment by Floowy** [comment]
> so habe ich es drin stehen
> 
> ```
> <manureSystemConnectors **rootNode="1|1|2|0"**>
>     <connector type="coupling" node="1|1|2|1" lockAnimationIndex="1" manureFlowAnimationIndex="2"/>
> </manureSystemConnectors>
> ```

**Comment by TRLPmarkus** [comment]
bei mir liegt die 20 und 21 untereinander

**Comment by Floowy** [comment]
> bei mir liegt die 20 und 21 untereinander

Klick doch mal im GE den lockPartFront an und schau bei Attributes ob da ein Haken bei Rigid Body ist, wenn ja dann schreib oder kopier von mir aus den rootNode Eintrag so hin wie ich es geschrieben habe. Sollte der 1|1|2|0 kein Rigid Body sein dann schau nach dem darüber also lockPart, wenn der nen Rigid Body ist, änder den rootNode ab auf 1|1|2

**Comment by TRLPmarkus** [comment]
ok danke dir

**Comment by TRLPmarkus** [comment]
leiter bleibt der fehler bestehen anpassung gemacht wie oben geschrieben wurde

**Comment by stijnwop** [comment]
Use a correct physics node as rootNode entry..

Make sure it's scaled correctly to 1 on all axis. If that's not the case freeze the scale of the given rootNode.

**Comment by TRLPmarkus** [comment]
![güllenlageraufbau1](https://user-images.githubusercontent.com/55022079/78431751-84d4a100-7675-11ea-87dd-baaba1f82d5a.png)
![güllenlageraufbau](https://user-images.githubusercontent.com/55022079/78431767-8605ce00-7675-11ea-81fe-40ba97e3ac14.png)
![güllenlageraufbau2](https://user-images.githubusercontent.com/55022079/78431777-869e6480-7675-11ea-8937-c41cfd20a3aa.png)

wie auf den bilder zu sehen ist alles auf 1 scalliert

**Comment by stijnwop** [comment]
And whats your current XML entry?

I would use the connector_vis as rootNode in this case as those other parts shown in the images most likely will be animated.

**Comment by TRLPmarkus** [comment]
ja alles ist animiert so dann habe ich jetzt auf connector_vis gemacht einträge in der xml angepast doch bleibt der schlauch wie am anfang

![fsScreen_2020_04_04_15_14_38](https://user-images.githubusercontent.com/55022079/78451823-1947ff00-7688-11ea-9c5a-963615cad0c5.png)

**Comment by stijnwop** [comment]
Okay as we're not getting futher.

Add everything what you did in a zip and show us your log.

**Comment by TRLPmarkus** [comment]
wie soll ich dir alles zu kommen lassen ??

**Comment by stijnwop** [comment]
Zip it and drop it here..

**Comment by TRLPmarkus** [comment]
[GuelleLager.zip](https://github.com/stijnwop/manureSystem/files/4431531/GuelleLager.zip)
so mal das komplette lager

**Comment by TRLPmarkus** [comment]
[log.txt](https://github.com/stijnwop/manureSystem/files/4431609/log.txt)

**Comment by TRLPmarkus** [comment]
noch die log dazu

**Comment by stijnwop** [comment]
Hey, all good and stuff.. but that zip didn't work at all.

Well after some fixes I came to conclusing the custom rootNode isn't loaded currectly all the time

So it's fixes when you freeze the scale of Drahttaun_Element_mit_Pfosten to 1 or when you update the manure system with the current github version.

**Comment by TRLPmarkus** [comment]
ok wenn ich richtig verstehen den zaun auf 1 scalieren sollte der fehler rasu sein ??
oder die version von hier runder laden ??

**Comment by stijnwop** [comment]
Richtig

**Comment by TRLPmarkus** [comment]
ok danke dir kann mann es den auch festverbauen da ch nicht so auf placierbache sache stehen da ich es ja auch auf meiner map fest verbauen möchte
