### ISSUE TITLE
ManureSystemAvailabilityCheck.lua'. error 

### ISSUE THREAD

**Issue by Ralleran** [stijnwop/manureSystem#67]
Hallo ich würde mich über hilfe sehr freuen.. 
[log.txt](https://github.com/stijnwop/manureSystem/files/4429637/log.txt)

**Comment by stijnwop** [comment]
.. read the manual.

https://github.com/stijnwop/manureSystem/blob/master/docs/PLACEABLES.md#adding-the-manuresystemavailabilitycheck

Add the script to your mod and source it. In your log it clearly shows that the script is not precent on the given patch.
