### ISSUE TITLE
Weight of pump keep increasing if pumping while unconnected

### ISSUE THREAD

**Issue by atledreier** [stijnwop/manureSystem#68]
I noticed that I sometimes couldn't lift the pump with my tractor, and started looking into the weight.

How to reploduce: Place the pump next to a water trigger with hoses attached to the pump only. Start pumping. The pump will start, and the weight of the pump will rise. I stopped at 20 tons, but it looked to keep going.

**Comment by stijnwop** [comment]
Hey, 

Are you running any additional scripts that affect mass?
Cause there's for starters nothing in the manure system script that does direct impact on the mass.

Did some analysing.. and did not notice any mass change on the pump
![fsScreen_2020_04_04_15_52_54](https://user-images.githubusercontent.com/12030020/78452635-983f3680-768c-11ea-9a9a-de7012282434.png)

**Comment by atledreier** [comment]
I am not running any mods that change mass, I did a test save to check just that.

I just did a game with the manure system and a pump. Hooked up two hoses, one to each outlet on the pump, drove up to a water trigger, and started the pump. After a little while my tractor nodsedove due to the weight of the pump (I had it on the front hydraulic).

This is with two loose end of hose, one end close to a water trigger, the other just loose on the ground.

**Comment by atledreier** [comment]
![fsScreen_2020_04_04_16_16_46](https://user-images.githubusercontent.com/54736373/78453097-dc800600-768f-11ea-83f6-649fc42f2b2f.png)

**Comment by stijnwop** [comment]
Interesting, where did you get that water trigger from? :)

**Comment by atledreier** [comment]
It's the vanilla placeable.

**Comment by stijnwop** [comment]
That one does not support hose couplings?

**Comment by atledreier** [comment]
I haven't tried. The one I use in my main game doesn't. And the water trailer I use doesn't either. That's how I discovered this in the first place. I figured I'd start the pump and THEN try to connect the hoses, and after a few seconds my tractor was on it's nose..  XD

**Comment by stijnwop** [comment]
Oh got it, it's not Manure system related.. it's because the pump can be refilled due to a missing fill unit setting.
I will add this on the list for the pump in a future update. 

Closing.
