### ISSUE TITLE
Issue adding manure system to a manure storage

### ISSUE THREAD

**Issue by goshdanny** [stijnwop/manureSystem#71]
Hi there,
Ive been modifying manure systems on some maps that Ive been playing and successful managed to add manure pipelines to pump objects and end up with an issue adding manure system to this manure storage placeable. Can anyone help me modify this manure storage file?
[slurryStorage.zip](https://github.com/stijnwop/manureSystem/files/4435994/slurryStorage.zip)

**Comment by stijnwop** [comment]
What about explaining the issue?

**Comment by goshdanny** [comment]
The issue is that manure connectors dont work under manure storage . I tried to follow instructions and edit xml. And it doesnt work.
![Untitled1](https://user-images.githubusercontent.com/63223277/78533880-002c8300-782d-11ea-98d6-425107632ea8.png)

**Comment by goshdanny** [comment]
I uploaded edited XML for a slurry storage

[slurryStorage.zip](https://github.com/stijnwop/manureSystem/files/4436637/slurryStorage.zip)
