### ISSUE TITLE
Hose only connects when machine is folded up.

### ISSUE THREAD

**Issue by Bullitt33** [stijnwop/manureSystem#73]
Hello all,

I seem to be having an issue where I can only attach the fert hose to my machine (planter) when it is folded (transport mode). When the machine is unfolded in work mode it refuses to let me attach the hose. Anybody have any recommendations? I am lost on this and have tried everything I can think of over the past 3-4 days. I will attach some pictures to demonstrate my issue.

![fsScreen_2020_04_07_00_06_15](https://user-images.githubusercontent.com/63276513/78629311-a6e04600-7864-11ea-9b35-f78478c501a4.png)
![fsScreen_2020_04_07_00_09_40](https://user-images.githubusercontent.com/63276513/78629318-a9db3680-7864-11ea-82ce-8f57dc70d24b.png)
![fsScreen_2020_04_07_00_09_58](https://user-images.githubusercontent.com/63276513/78629322-acd62700-7864-11ea-870d-efd7c47d1a30.png)

**Comment by stijnwop** [comment]
Well there's no fold limit or whatever.

One thing I could think of is a collision issue, how does that look in the planter?

Secondly, can you share the entries you used here.

**Comment by stijnwop** [comment]
Well there's no fold limit or whatever.

One thing I could think of is a collision issue, how does that look in the planter?

Secondly, can you share the entries you used here.

**Comment by Bullitt33** [comment]
Wopster I have attached the pics of collisions below and also added a download link for the modDesc and XML of the planter. If you need a i3d of the mod as well let me know and I can get you that as well.

Mod Desc & XML DL link
https://www.dropbox.com/s/mk7gzpeljvlcmro/modDesc%20%26%20XML.zip?dl=0

![1](https://user-images.githubusercontent.com/63276513/78690864-fc990a80-78c5-11ea-9e52-515cde10c314.png)
![2](https://user-images.githubusercontent.com/63276513/78690870-fd31a100-78c5-11ea-91cb-7d5d8bbf3670.png)
![3](https://user-images.githubusercontent.com/63276513/78690874-fdca3780-78c5-11ea-8f36-6b91cf123ff0.png)
![4](https://user-images.githubusercontent.com/63276513/78690875-fe62ce00-78c5-11ea-967b-b3e8c0775b8d.png)

**Comment by Bullitt33** [comment]
Issue has been resolved. The original creator of the mod had some translations messed up and had to be set
