### ISSUE TITLE
Callstack "getCollisionMask" if using chainsaw or lifting things by hand

### ISSUE THREAD

**Issue by DerLou** [stijnwop/manureSystem#74]
Unfortunately I have a call stack. Log is attached.
This error always occurs when I use the chainsaw or lift tree trunks by hand. There are 2 hoses on the cowshed, but they are not connected to each other.
[log.txt](https://github.com/stijnwop/manureSystem/files/4446573/log.txt)

**Comment by KITT3000** [comment]
Why are you writing an error here without downloading a newer version from here?

**Comment by stijnwop** [comment]
Can't reproduce with the current github version..
