### ISSUE TITLE
added connector isnt working when buy an mod with added support

### ISSUE THREAD

**Issue by joshvzeyl** [stijnwop/manureSystem#76]
hello all

i added an connector to an mod the connector is visible when i use the command in the store but when i buy it isn't there any suggestion how i can fix it??
![fsScreen_2020_04_09_20_11_20](https://user-images.githubusercontent.com/26695249/78927140-a7642100-7a9e-11ea-8c17-dfd3dd277689.png)
![fsScreen_2020_04_09_20_12_04](https://user-images.githubusercontent.com/26695249/78927147-aaf7a800-7a9e-11ea-9d11-f1fd58818278.png)

**Comment by stijnwop** [comment]
Link to the mod?

**Comment by joshvzeyl** [comment]
https://drive.google.com/file/d/1m7US4kbNmvNQn6MKjUK6ryrU_7j7-dY7/view?usp=sharing
