### ISSUE TITLE
Placeable.lua(1224) : attempt to index local 'storeItem'

### ISSUE THREAD

**Issue by Vanquish081** [stijnwop/manureSystem#77]
Added manure system to BGA if the manureSystem mod isn't in mod folder show this error and the rest storeItem show error Placeable.lua (1094). Am I doing something wrong?

No all users have manureSystem or like this mod, this error isn't solved? Am I doing something wrong?

I was going to go crazy last night looking because I had all the storeItem with error when I tried the map without mods....

**Comment by stijnwop** [comment]
Read the documention, specially the part on the ManureSystem vailability check..

https://github.com/stijnwop/manureSystem/blob/master/docs/PLACEABLES.md#adding-the-manuresystemavailabilitycheck

**Comment by Vanquish081** [comment]
Well... then work fine if I delete script for ManureSystemAvailabilityCheck in modDesc.xml?

**Comment by stijnwop** [comment]
Your BGA is a mod? If yes you need the ManureSystemAvailabilityCheck.

If it's a map BGA or husbandry you don't need it.

**Comment by Vanquish081** [comment]
Is integrated in a map, but this map include farmSilo for slurry and liquid to which I want to add this function

**Comment by stijnwop** [comment]
Mm, not sure how your setup is.. probably as custom store item.
If it's a store item in anyway, you will need that check.
If it's just loaded in the items.xml with the vanilla placeable type it's not needed.

**Comment by Vanquish081** [comment]
Ok, I will continue testing
Could ManureSystemAvailabilityCheck.lua display a log message for these cases? because not shown in the log: Warning: ManureSystem is missing. %s will be removed from the store

**Comment by stijnwop** [comment]
So how are you adding it to your map?
As an additional storeItem? Or only over the items.xml?

`<placeableType>FS19_manureSystem.manureSystemStorage</placeableType>` Is needed in order to work with the ManureSytem.

The ManureSystemAvailabilityCheck already will give you a log warning, if the placeable is added as a storeItem.

**Comment by Vanquish081** [comment]
Is added to items.xml and in the section storeItem in modDesc.

I use ``<placeableType>FS19_manureSystem.manureSystemStorage</placeableType>`` and no show error, but no connect the hose.

**Comment by Snickers125** [comment]
Did you change the item className="FS19_manureSystem.ManureSystemStorage" within the defaultItems?

**Comment by Vanquish081** [comment]
I've changed it now and it doesn't work either.

I'm going to go over the xml lines and the indexs.
