### ISSUE TITLE
One connector on one lagoon which is used by two husbandries

### ISSUE THREAD

**Issue by Floowy** [stijnwop/manureSystem#78]
Like the title shows, I need a suggestion how to realize this or at least the hint that this isn't possible. 

The situation, there are 2 build-in husbandries that are using 1 lagoon for storing liquidManure, with separate triggers etc. Placing 2 connectors looks a little bit weird. The husbandries have also separated xml's. 

So is it possible to set 1 connector for both or do I need 2 connectors?

**Comment by stijnwop** [comment]
Euhm, no thats not possible.

As there's no way to differenciate between them, cause both will have the same fillType and I am not planning on adding an option to choose what source to take.

So you will need two connectors, 1 for each husbandry.

**Comment by Floowy** [comment]
Ok, thx for clear this out :)
