### ISSUE TITLE
liquid manure pumping into bga

### ISSUE THREAD

**Issue by Floowy** [stijnwop/manureSystem#79]
Hello wopster, again a short question, maybe a stupid one. It's not possible to pump liquid manure into a bga? Always getting the message "pump material is not supported".

Not sure if this is an issue or not, maybe it's not inteded to be able to pump liquid manure into a BGA.
I´'m little confused about it.

**Comment by stijnwop** [comment]
Well, the BGA you're trying to pump to only supports digestate .. that's why.

Fully depends on how that object is setup, so no issue at all.

**Comment by Floowy** [comment]
Well, that's not the problem, like you can see in the part of the xml
`<bga>

        <bunker>
            <unloadingStation node="0|0|0" stationName="$l10n_station_bgaBunker" appearsOnPDA="true" appearsOnStats="true" storageRadius="0" >
                <unloadTrigger exactFillRootNode="0" baleTriggerNode="1"/>
            </unloadingStation>

            <slot capacity="100000" litersPerSecond="30" >
                <fillType fillTypes="silage manure pomace" scale="0.4" pricePerLiter="0.5"/>
                <fillType fillTypes="grass_windrow dryGrass_windrow" scale="0.2" pricePerLiter="0.1"/>
                <display baseNode="0|0|1" />
            </slot>
            <slot capacity="150000" litersPerSecond="10">
                <fillType fillTypes="liquidManure" scale="0.3" pricePerLiter="0.4"/>
            </slot>
        </bunker>`

**Comment by stijnwop** [comment]
Slots are input.. not output.

**Comment by Floowy** [comment]
Yes and I want to put in liquidManure into the BGA. No issue when using any liquid manure barrel with giving LM to the BGA via the normal input trigger, only the manure system connector isn't working for input
