### ISSUE TITLE
Mod Conflict with GtX's Shelf Storage Mod on the ModHub

### ISSUE THREAD

**Issue by cwattyeso** [stijnwop/manureSystem#80]
Just discovered today in game that with the Manure System Mods activated it breaks part of GtX's Shelf Storage Mod. Specifically it breaks the Liquid Shelf Storage component of his Mod. With the Manure System Active his Pallet Racking will not accept the Liquid or Herbicide Pallets purchased from the Store or created by Global Company Buildings.

**Comment by Irving-75** [comment]
Yes! I hhave the same problem, and it's almost unfixable (by me). I tried to uninstall manure system but if I do that the savegame doesn't load anymore, is there a way to uninstall it? or make both work? There's another issue here, it seems like it messes with the trigger.

**Comment by stijnwop** [comment]
Alright, let me look into it

**Comment by Larman** [comment]
> Yes! I hhave the same problem, and it's almost unfixable (by me). I tried to uninstall manure system but if I do that the savegame doesn't load anymore, is there a way to uninstall it? or make both work? There's another issue here, it seems like it messes with the trigger.


If you really want to do without the Manure system you have to remove all palettes (herbecide and liquid fertilizer) from the map. Then you can remove Manure and the savegame runs normally

**Comment by Irving-75** [comment]
Hello, I also found that if you remove the "real dirt" mod, after you disable manure, it let's you in to the savegame without removing any pallets, the game works fine and the shelf storage works again. I hope this helps to find the problem or conflict with the mods

**Comment by cwattyeso** [comment]
I've also found the Manure System conflicts and breaks the functionality of the Palett Storage Pack https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=141909&title=fs2019 again Liquid Fertiliser and Herbicide Pallets can't be loaded into the buildings provided by the mod, as they are no longer recognised.

I'm guessing the Default ingame Pallets have been messed or tampered with by the Manure System Mod and they now are either a different size, ID or something and that screws up compatibility with every other mods that uses the default models & objects.

**Comment by stijnwop** [comment]
So dived into the issue a bit,
I am altering the vanilla liquid pallets to support the manure system by adding a second fill unit configuration to have the option to refill them.

Now cause of me doing that the vehicle type name changed, but the trigger callback in his mod does a dirty hard check on "pallet" .. unlike some things do from Giants (e.g. the treeplanter)

Which causes his mod to not recognize the pallets anymore cause of that hard check.. meaning any other mod that does something with that will cause the same issue.

I contacted GTX to see with what solution we come up with, I porpused some already.

**Comment by stijnwop** [comment]
[ObjectStorage.zip](https://github.com/stijnwop/manureSystem/files/4550998/ObjectStorage.zip)

Replace the script in the shelf storage mod with the script included in the zip above. ;)
Minor tweak was required.

**Comment by stijnwop** [comment]
Mod has been updated:
https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=141308&title=fs2019

**Comment by SFRacing** [comment]
The issue is active again, if CSZ Equipment Pack by DD ModPassion is active.

The Liquid Storage Shelf works fine with only CSZ or Manure active. But does'nt when both are active.

I don't know, if this is the right place for this issue, but I tracked it down to the 3 mods and want to put it outthere somewhere.
