### ISSUE TITLE
Support for other Giants Software mods

### ISSUE THREAD

**Issue by IceUul** [stijnwop/manureSystem#87]
Please add support to other Giants Software mods also.
Have support for Briri Field Master 20 mod and Holmer DLC, please also include
the hose support for following other Giants Software mods in modhub:
Slurry container - ITRunner Pack
Sprayer - Caruelle Nicolas Stilla 460
Sprayer - Amazone Pantera 4502
Sprayer - New Holland SP400F
Slurry spreader and transporter - Horsch Pack
Sprayer - Horsch Leeb PT350 - Horsch Pack

**Comment by Snickers125** [comment]
any suggestions of positions? Cause most of them got the connectors under lids or something like that.

**Comment by IceUul** [comment]
All the slurry equipment already got the connectors but sprayers need them to be added. 
To be noted, that other sprayers also got them added by manureSystem mod, so i guess place on
side or under equipment that is suitable for these connectors, there are not much choices.

**Comment by stijnwop** [comment]
Horsch pack and Kverneland pack has been added.
