### ISSUE TITLE
question adding slurry and digstate in the same storage

### ISSUE THREAD

**Issue by dehjvg** [stijnwop/manureSystem#88]
question is it some how possible to put some tanks of slurry and some tanks of digistate in the same slurry lagoon?

i know i the real world this happens alot to mix both. i also know normal this is not possible in farming would be nice if there would be a way to do it

**Comment by stijnwop** [comment]
I know thats a thing in real life, but how thats done in FS I don't see this being implemented in the future.

As digistate is a different substance lacking minerals that slurry does have (IRL) I would consider it cheating if we mix this in the game and let the output be determined based on what filltype prevails over the other.
