### ISSUE TITLE
LUA update Error "attempt to call method 'getFillArms' (a nil value)"

### ISSUE THREAD

**Issue by djtwist** [stijnwop/manureSystem#89]
Using version: 1.0.9.0-beta

While trying to change pump from "filling" to "emptying" with the "Z" key, you end up with a LUA error. 

Error: Running LUA method 'update'. 
FS19_manureSystem/src/vehicles/ManureSystemFillArm.lua:249: attempt to call method 'getFillArms' (a nil value)

I tested this with no mods except manureSystem and the following equipment but I am sure this function would happen on any tanks.
"New Holland T5.100 + Kuhn PF 1500 (Front liquid Fert Tank)"

**Comment by FarmerAndy** [comment]
I have the same problem with my trailers since the new master version, but the 1.0.0.9beta from Assets3 does not have this problem. The error message appears when you try to change the pump direction by pressing a key.

**Comment by stijnwop** [comment]
Ugh stupid me, fixed.

**Comment by FarmerAndy** [comment]
Thanks a lot your support is great

**Comment by stijnwop** [comment]
Glad to hear!
