### ISSUE TITLE
Can't pump from slurry pit to slurry lagoon

### ISSUE THREAD

**Issue by Miketeg** [stijnwop/manureSystem#91]
Hi, yesterday I was trying to pump from slurry pit (Lakeland Valley v11 by Stevie) to the Slurry Lagoon.

- My pump is connected to the tractor
- all my pipe are well connected
- all the manure flow are open (Pump x2 + slurry lagoon)
- My tractor is running
- I'm pumping from left to right (I tried right to left and same thing)

Problem is that I can't get the "R" to start pumping.

Is it possible to pump from a pit to the lagoon ?

<img width="605" alt="2020-04-30 16_35_20-Steam" src="https://user-images.githubusercontent.com/26671838/80804834-5ec2f380-8b84-11ea-8696-f5da2b4573bf.png">
<img width="506" alt="2020-04-30 16_39_56-Steam" src="https://user-images.githubusercontent.com/26671838/80804836-5f5b8a00-8b84-11ea-9e9a-e7bcab3ba4be.png">

**Comment by stijnwop** [comment]
Yes it sure it possible.. the pit is filled?

**Comment by Miketeg** [comment]
Yes, it has 800 000 liters in it. I tried both pit (that are both full) and none of them are working.

**Comment by stijnwop** [comment]
You're running the github version?

**Comment by Miketeg** [comment]
Yes i'm runing the latest one, that was commited 2 days ago.

**Comment by Miketeg** [comment]
By the way, I just tried to fill a wagon with this setup and it works A1.

**Comment by stijnwop** [comment]
Ah found it, should be fixed now. :)

**Comment by Miketeg** [comment]
Thanks will give it a try !

**Comment by Miketeg** [comment]
It works perfect ! Thanks Wopster
