### ISSUE TITLE
Make the use of the mod mandatory

### ISSUE THREAD

**Issue by Scozor** [stijnwop/manureSystem#96]
Hello,

I have a question, is it possible to make the mod mandatory, for example on my server, players can fill their sprayer with liquid fertilizer directly from the cabin by pressing a key (default behavior of FS19 ).

Is it possible to disable this default behavior and force players to use the pipes?

Thank you and sorry for my English.

**Comment by KITT3000** [comment]
Duplicate #27

**Comment by Scozor** [comment]
I looked before posting, sorry
