### ISSUE TITLE
"Trigger" for hose to add

### ISSUE THREAD

**Issue by fresH229a** [stijnwop/manureSystem#97]
Hey,

is there any special entry I miss.
I need to move the hose "into" the vehicle, that it will be recognized.

It will be plugged in correctly after that but the trigger which gives me the command is not at the Hose connection

**Comment by stijnwop** [comment]
Hi, 

A bit more context would be nice.. I am no fortune teller.

What are you trying todo? Preparing your own mod? Using a mod that I prepared?
Pictures?

With only a brief description like that I can't do much.

**Comment by fresH229a** [comment]
![Unbenannt](https://user-images.githubusercontent.com/35875328/81613386-aea08680-93de-11ea-9baa-7c7b8e05699f.png)

I am trying to add it to the FSM Tank.

See in the pictures.

**Comment by stijnwop** [comment]
How is that collision setup for that tank?

**Comment by fresH229a** [comment]
Thats a bit weird.
I am not the best in i3d and FSM take a strange approach to handle this tank.

https://1drv.ms/u/s!Al7jqt4EitT9tirN-yelz9I8gDC6?e=gL8YH1

Thats the mod.
